import {and,desc,eq} from 'drizzle-orm';
import {db} from '@/core/db';import {qrCodes,travelerUsers,visits,trips,tripDays} from '@/core/db/schema';import type {Actor} from '@/core/auth/permissions';import {sanitizeId} from '@/core/security/sanitize';import {getTripById} from '@/modules/trips/repository';import {publicContent} from '@/modules/content/repository';
export function isQrDuplicate(last:Date|undefined,now:Date,minutes:number){return !!last&&now.getTime()-last.getTime()<minutes*60000;}
function localDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
export async function resolveQr(code:string){let clean:string;try{clean=sanitizeId(code,'Código QR');}catch{return null;}const database=await db();const [qr]=await database.select().from(qrCodes).where(eq(qrCodes.code,clean));if(!qr)return null;const place=(await publicContent('places')).find(p=>p.id===qr.placeId);return place?{qr,place}:null;}
async function ensureVisitTrip(actor:Actor,requested?:string){const database=await db();const today=localDate();if(requested){try{const clean=sanitizeId(requested,'Viagem');await getTripById(clean,actor);return clean;}catch{}}
 const [current]=await database.select().from(trips).where(eq(trips.owner,actor.id)).orderBy(desc(trips.updatedAt)).limit(1);if(current?.startsOn&&current.endsOn&&current.startsOn<=today&&current.endsOn>=today)return current.id;
 const id=crypto.randomUUID();await database.transaction(async tx=>{await tx.insert(trips).values({id,owner:actor.id,version:1,synthetic:false,cityId:'city-serra-negra-sp',startsOn:today,endsOn:today,party:'solo',pace:'balanced',transport:'unknown',interests:[],intentions:[],needs:[],updatedAt:new Date()});await tx.insert(tripDays).values({id:`${id}-day-1-${today}`,tripId:id,date:today,sortOrder:0});});return id;
}
export async function registerQrVisit(actor:Actor,code:string,tripId?:string){if(actor.role!=='tourist')throw new Error('Entre como viajante para registrar a visita.');const database=await db();const resolved=await resolveQr(code);if(!resolved)throw new Error('QR inválido.');if(resolved.qr.status!=='active')throw new Error('Este QR está desativado.');const [traveler]=await database.select().from(travelerUsers).where(eq(travelerUsers.id,actor.id));if(!traveler)throw new Error('Perfil de viajante indisponível.');const previous=await database.select().from(visits).where(and(eq(visits.travelerUserId,traveler.id),eq(visits.placeId,resolved.place.id))).orderBy(desc(visits.occurredAt));const last=previous[0];if(isQrDuplicate(last?.occurredAt,new Date(),resolved.qr.dedupeWindowMinutes))return{visit:last,deduplicated:true,place:resolved.place};const effectiveTripId=await ensureVisitTrip(actor,tripId);const trip=await getTripById(effectiveTripId,actor);const outside=!trip.data.days.some(day=>day.items.some(item=>item.placeId===resolved.place.id&&item.state!=='removed'));const row={id:crypto.randomUUID(),tripId:effectiveTripId,travelerUserId:traveler.id,placeId:resolved.place.id,occurredAt:new Date(),evidence:'qr',visitNumber:previous.length+1,outsidePlannedRoute:outside,synthetic:false};await database.insert(visits).values(row);return{visit:row,deduplicated:false,place:resolved.place};}
