'use server';
import {and,eq} from 'drizzle-orm';import {revalidatePath} from 'next/cache';import {redirect} from 'next/navigation';
import {db} from '@/core/db';import {alerts,audit,partnerMaturityHistory,partnerRequests,qrCodes} from '@/core/db/schema';import {requireAdmin} from '@/core/auth/admin';import {sanitizeId,sanitizeNarrative,publicErrorMessage} from '@/core/security/sanitize';import {routeFor} from './fields';import {commitContent} from './service';import {kinds,type Kind} from '@/modules/content/repository';
export async function saveContent(_state:{message:string;ok?:boolean},form:FormData){try{const actor=await requireAdmin();const kind=String(form.get('kind')) as Kind;if(!kinds.includes(kind))throw new Error('Tipo inválido.');const operation=String(form.get('operation')||'draft');if(!['draft','publish','archive','review','restore'].includes(operation))throw new Error('Ação inválida.');const id=sanitizeId(form.get('id'),'Conteúdo');const version=Number(form.get('version'));if(!Number.isInteger(version)||version<0)throw new Error('Versão inválida.');await commitContent(kind,operation,id,version,form,actor);revalidatePath('/','layout');return{message:({draft:'Rascunho salvo. O público permanece na versão publicada.',publish:'Conteúdo publicado.',archive:'Conteúdo arquivado.',review:'Marcado para revisão.',restore:'Versão restaurada como novo rascunho.'} as Record<string,string>)[operation],ok:true};}catch(error){const message=publicErrorMessage(error,'Não foi possível salvar. Confira o slug e os relacionamentos.');return{message,ok:false};}}
export async function createContent(form:FormData){await requireAdmin();const kind=String(form.get('kind')) as Kind;if(!kinds.includes(kind))throw new Error('Tipo inválido.');redirect(`/admin/${routeFor(kind)}/novo`);}
export async function reviewPartnerRequest(form:FormData){const actor=await requireAdmin();const id=sanitizeId(form.get('id'),'Solicitação');const status=String(form.get('status'));if(!['approved','rejected'].includes(status))throw new Error('Estado inválido.');const database=await db();const [row]=await database.select().from(partnerRequests).where(eq(partnerRequests.id,id));if(!row)throw new Error('Solicitação não encontrada.');await database.transaction(async tx=>{await tx.update(partnerRequests).set({status,reviewedBy:actor.id,reviewedAt:new Date()}).where(and(eq(partnerRequests.id,id),eq(partnerRequests.status,'pending')));await tx.insert(audit).values({id:crypto.randomUUID(),actor:actor.id,action:`partner_request_${status}`,entity:id,before:{status:row.status,requestType:row.requestType,partnerId:row.partnerId},after:{status}});});revalidatePath('/admin/solicitacoes');}
export async function setQrStatus(form:FormData){const actor=await requireAdmin();const id=sanitizeId(form.get('id'),'QR');const status=String(form.get('status'));if(!['active','disabled'].includes(status))throw new Error('Estado inválido.');const database=await db();const [before]=await database.select().from(qrCodes).where(eq(qrCodes.id,id));if(!before)throw new Error('QR não encontrado.');await database.transaction(async tx=>{await tx.update(qrCodes).set({status}).where(eq(qrCodes.id,id));await tx.insert(audit).values({id:crypto.randomUUID(),actor:actor.id,action:'qr_status_changed',entity:id,before:{status:before.status,placeId:before.placeId},after:{status}});});revalidatePath('/admin/qr');}
export async function recordMaturity(form:FormData){const actor=await requireAdmin();const partnerId=sanitizeId(form.get('partnerId'),'Parceiro');const stage=String(form.get('stage'));const dataMaturity=String(form.get('dataMaturity'));const reason=sanitizeNarrative(form.get('reason'),1000)||null;const allowedStages=['Entrada','Ativação','Primeiros dados','Engajamento','Consistência','Maturação'];const allowedData=['DADO INICIAL','SINAL','PADRÃO','INSIGHT','OPORTUNIDADE','HIPÓTESE EM TESTE','APRENDIZADO VALIDADO'];if(!allowedStages.includes(stage)||!allowedData.includes(dataMaturity))throw new Error('Estágio inválido.');const database=await db();await database.transaction(async tx=>{await tx.insert(partnerMaturityHistory).values({id:crypto.randomUUID(),partnerId,stage,dataMaturity,reason});await tx.insert(audit).values({id:crypto.randomUUID(),actor:actor.id,action:'partner_maturity_recorded',entity:partnerId,after:{stage,dataMaturity}});});revalidatePath('/admin/maturacao');}
export async function resolveAlert(form:FormData){const actor=await requireAdmin();const id=sanitizeId(form.get('id'),'Alerta');const database=await db();await database.transaction(async tx=>{await tx.update(alerts).set({status:'resolved',resolvedAt:new Date()}).where(eq(alerts.id,id));await tx.insert(audit).values({id:crypto.randomUUID(),actor:actor.id,action:'alert_resolved',entity:id,after:{status:'resolved'}});});revalidatePath('/admin/maturacao');}
