'use server';
import {cookies} from 'next/headers';import {redirect} from 'next/navigation';import {revalidatePath} from 'next/cache';import {eq,and} from 'drizzle-orm';
import {db} from '@/core/db';import {content,audit,type ContentData} from '@/core/db/schema';import {requireAdmin,secret} from '@/core/auth/admin';import {signDemoToken} from '@/core/auth/token';import {assertDemo} from '@/providers';import {formDataToContent,routeFor} from './fields';import {validateContent} from './validation';import {kinds,type Kind} from '@/modules/content/repository';
export async function loginDemo(){assertDemo();(await cookies()).set('demo-admin',signDemoToken(secret()),{httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production',path:'/',maxAge:4*60*60});redirect('/admin');}
export async function logoutDemo(){(await cookies()).delete('demo-admin');redirect('/admin');}
export async function saveContent(_state:{message:string;ok?:boolean},form:FormData){try{const actor=await requireAdmin();const kind=String(form.get('kind')) as Kind;if(!kinds.includes(kind))throw new Error('Tipo inválido.');const operation=String(form.get('operation')||'draft');if(!['draft','publish','archive','review','restore'].includes(operation))throw new Error('Ação inválida.');const id=String(form.get('id'));const version=Number(form.get('version'));const database=await db();await database.transaction(async tx=>{
const [row]=await tx.select().from(content).where(and(eq(content.id,id),eq(content.kind,kind)));
if(row&&row.version!==version)throw new Error('Outra edição foi salva. Atualize antes de continuar.');if(!row&&operation!=='draft')throw new Error('Salve o rascunho antes.');
let draft:ContentData=row?.draft||{id,synthetic:true,cityId:'city-demo-serra-negra'};
if(operation==='draft')draft=validateContent(kind,formDataToContent(kind,form,draft));
if(operation==='restore'){const [entry]=await tx.select().from(audit).where(and(eq(audit.id,String(form.get('restoreId'))),eq(audit.entity,id)));const restored=entry?.after as {draft?:ContentData}|null;if(!restored?.draft)throw new Error('Versão indisponível.');draft=validateContent(kind,restored.draft);}
if(operation==='publish')validateContent(kind,draft);
if(['draft','publish'].includes(operation)){
for(const [relation,ids] of [['places',draft.placeId?[draft.placeId]:[]],['categories',draft.categoryIds||[]],['sources',draft.sourceIds||[]]] as [string,string[]][]){for(const ref of ids){const [linked]=await tx.select().from(content).where(and(eq(content.id,ref),eq(content.kind,relation)));if(!linked||linked.status==='archived'||(operation==='publish'&&!linked.published))throw new Error(`Relacionamento indisponível: ${ref}`);}}
if(kind==='partners'&&draft.placeId){const [linked]=await tx.select().from(content).where(eq(content.id,draft.placeId));draft.name=linked?.draft.name;draft.slug=linked?.draft.slug;}
}
const values={id,kind,slug:draft.slug||id,draft,status:operation==='publish'?'published':operation==='archive'?'archived':operation==='review'?'needs_review':'draft',published:operation==='publish'?draft:row?.published||null,version:(row?.version||0)+1,synthetic:true};
if(row){const updated=await tx.update(content).set(values).where(and(eq(content.id,id),eq(content.version,version))).returning();if(!updated.length)throw new Error('Conflito de versão. Atualize a página.');}else await tx.insert(content).values(values);
await tx.insert(audit).values({id:crypto.randomUUID(),actor:actor.id,action:operation,entity:id,before:row||null,after:values});
});revalidatePath('/','layout');return{message:({draft:'Rascunho salvo. O público permanece na versão publicada.',publish:'Conteúdo publicado.',archive:'Conteúdo arquivado.',review:'Marcado para revisão.',restore:'Versão restaurada como novo rascunho.'} as Record<string,string>)[operation],ok:true};}catch(error){const message=error instanceof Error?error.message:'';return{message:message.includes('duplicate')||message.includes('Failed query')?'Não foi possível salvar. Confira o slug e os relacionamentos.':message||'Falha ao salvar.',ok:false};}}
export async function createContent(form:FormData){await requireAdmin();const kind=String(form.get('kind')) as Kind;if(!kinds.includes(kind))throw new Error('Invalid kind');redirect(`/admin/${routeFor(kind)}/novo`);}
