import type {ContentData} from '@/core/db/schema';import type {Kind} from '@/modules/content/repository';
export type Field={key:string;label:string;type?:'text'|'textarea'|'number'|'select'|'multi';required?:boolean;options?:Array<{value:string;label:string}>;relation?:Kind};
const name:Field={key:'name',label:'Nome',required:true};const slug:Field={key:'slug',label:'Slug',required:true};const description:Field={key:'shortDescription',label:'Descrição curta',type:'textarea'};
const choices=(values:string[])=>values.map(value=>({value,label:({indoor:'Ambiente interno',outdoor:'Ao ar livre',mixed:'Misto',free:'Sem custo',paid:'Pago',paid_with_booking:'Pago com reserva',free_with_booking:'Gratuito com reserva',unknown:'Não informado',tourist_point:'Ponto turístico',business:'Estabelecimento',public_point:'Ponto público',partner:'Parceiro',listed_business:'Negócio listado',none:'Sem reserva',external_optional:'Reserva externa opcional',external_required:'Reserva externa obrigatória',within_1_hour:'Em até 1 hora',within_few_hours:'Em algumas horas',same_day:'No mesmo dia',one_business_day:'Um dia útil',partial:'Parcial',full:'Completa'} as Record<string,string>)[value]||value}));
const environment:Field={key:'environment',label:'Ambiente',type:'select',options:choices(['indoor','outdoor','mixed'])};
const cost:Field={key:'costType',label:'Tipo de custo',type:'select',options:choices(['free','paid','paid_with_booking','free_with_booking','mixed','unknown'])};
const duration:Field={key:'durationMinutes',label:'Duração em minutos',type:'number'};
const place:Field={key:'placeId',label:'Lugar relacionado',type:'select',relation:'places',required:true};
const sources:Field={key:'sourceIds',label:'Fontes',type:'multi',relation:'sources'};
export const fields:Record<Kind,Field[]>={
places:[name,slug,{...description,required:true},{key:'longDescription',label:'Conteúdo editorial',type:'textarea'},{key:'placeType',label:'Natureza do lugar',type:'select',options:choices(['tourist_point','business']),required:true},{key:'commercialRelation',label:'Relação comercial',type:'select',options:choices(['public_point','listed_business','partner']),required:true},{key:'categoryIds',label:'Categorias',type:'multi',relation:'categories'},environment,cost,duration,{key:'openingHours.text',label:'Horário demonstrativo'},{key:'location.display',label:'Localização demonstrativa'},{key:'location.lat',label:'Latitude sintética',type:'number'},{key:'location.lng',label:'Longitude sintética',type:'number'},{key:'accessibility',label:'Acessibilidade informada',type:'multi',options:choices(['partial','full'])},sources],
partners:[place,{key:'responseTime',label:'Tempo de resposta declarado',type:'select',options:choices(['within_1_hour','within_few_hours','same_day','one_business_day'])},{key:'demoContacts.website',label:'Site fictício'},{key:'demoContacts.whatsapp',label:'WhatsApp fictício'},{key:'demoContacts.phone',label:'Telefone fictício'},{key:'demoContacts.instagram',label:'Instagram fictício'}],
experiences:[name,slug,description,place,cost,duration,environment,{key:'bookingType',label:'Reserva',type:'select',options:choices(['none','external_optional','external_required'])}],
events:[name,slug,description,place,{key:'startsAt',label:'Início (ISO com fuso)',required:true},{key:'endsAt',label:'Fim (ISO com fuso)',required:true},cost,environment,sources],
categories:[name,slug,{key:'icon',label:'Ícone semântico'},{key:'enabled',label:'Habilitada',type:'select',options:[{value:'true',label:'Sim'},{value:'false',label:'Não'}]},{key:'sortOrder',label:'Ordem',type:'number'}],
sources:[{key:'sourceName',label:'Nome da fonte',required:true},{key:'sourceType',label:'Tipo da fonte',type:'select',options:choices(['synthetic_validation'])},{key:'verificationStatus',label:'Verificação',type:'select',options:choices(['demo_only','needs_review'])},{key:'sourceUrl',label:'URL da fonte fictícia'},{key:'verifiedAt',label:'Data da verificação (ISO com fuso)'},{key:'notes',label:'Observações',type:'textarea'}]
};
export const routeKinds:Record<string,Kind>={lugares:'places',parceiros:'partners',experiencias:'experiences',eventos:'events',categorias:'categories',fontes:'sources'};
export const kindLabels:Record<Kind,string>={places:'Lugares',partners:'Parceiros',experiences:'Experiências',events:'Eventos',categories:'Categorias',sources:'Fontes'};
export function routeFor(kind:Kind){return Object.entries(routeKinds).find(([,value])=>value===kind)?.[0]||'lugares';}
export function fieldValue(data:ContentData,key:string):unknown{let value:unknown=data;for(const part of key.split('.'))value=value&&typeof value==='object'?(value as Record<string,unknown>)[part]:undefined;return value;}
export function formDataToContent(kind:Kind,form:FormData,base:ContentData){const result=structuredClone(base) as ContentData & Record<string,unknown>;for(const field of fields[kind]){const raw=form.get(field.key);let value:unknown=field.type==='multi'?form.getAll(field.key).map(String):raw===null?'':String(raw).trim();if(field.type==='select'&&value==='')value=undefined;if(field.type==='number')value=value===''?undefined:Number(value);if(field.key==='enabled')value=value==='true';if(field.required&&!value)throw new Error(`${field.label}: preenchimento obrigatório.`);const [parent,child]=field.key.split('.');if(child){const existing=result[parent];result[parent]={...(existing&&typeof existing==='object'?existing:{}),[child]:value};}else result[parent]=value;}if(result.openingHours)result.openingHours.type='demo';if(kind==='sources')result.name=result.sourceName;result.synthetic=true;result.cityId='city-demo-serra-negra';return result;}
