import type {ReferenceKind} from './ReferencePage';
export function initializeReferencePage(root:HTMLElement,kind:ReferenceKind,navigate:(path:string)=>void){
 const controller=new AbortController();
 const timers:ReturnType<typeof setTimeout>[]=[];
 const one=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s);
 const all=<T extends HTMLElement=HTMLElement>(s:string)=>Array.from(root.querySelectorAll<T>(s));
 const listen=(target:EventTarget|null,event:string,handler:EventListener)=>target?.addEventListener(event,handler,{signal:controller.signal});
 const later=(fn:()=>void,delay:number)=>timers.push(setTimeout(fn,delay));
 let toastTimer:ReturnType<typeof setTimeout>;
 function toast(message:string){const el=one('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4000);}
 const scroll=(el:HTMLElement|null)=>el?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});
 const select=(s:string,chosen:HTMLElement,attribute='aria-pressed')=>all(s).forEach(el=>{el.classList.toggle('active',el===chosen);el.setAttribute(attribute,String(el===chosen));});
 all('button:not([type])').forEach(el=>el.setAttribute('type','button'));
 all('.interest-filters button,[data-network],[data-tab],[data-signal],[data-stage],.route-stop').forEach(el=>el.setAttribute('aria-pressed',String(el.classList.contains('active'))));
 listen(root,'click',event=>{
  const b=(event.target as HTMLElement).closest<HTMLElement>('button,a');if(!b||!root.contains(b))return;
  if(b instanceof HTMLAnchorElement&&b.getAttribute('href')?.startsWith('#')&&!b.getAttribute('href')?.startsWith('#/')){event.preventDefault();const target=one(b.getAttribute('href')!);if(target){target.tabIndex=-1;target.focus({preventScroll:true});scroll(target);}return;}
  if(b instanceof HTMLAnchorElement&&b.getAttribute('href')?.startsWith('/')){const mouse=event as MouseEvent;if(!mouse.ctrlKey&&!mouse.metaKey&&!mouse.shiftKey&&!mouse.altKey){event.preventDefault();navigate(b.getAttribute('href')!);}return;}
  if(b.matches('.ghost-card')){navigate(`/roteiro?interest=${b.closest('.path-card')?.getAttribute('data-tags')?.includes('cultura')?'cat-cultura':'cat-natureza'}`);return;}
  if(b.closest('[data-route-panel]')&&b.matches('[data-toast]')){const presets=['serra-negra-essencial-2-dias','fim-de-semana-a-dois','natureza-e-mirantes','cafes-e-sabores'];navigate(`/roteiros/${presets[Number(b.closest<HTMLElement>('[data-route-panel]')!.dataset.routePanel)]}`);return;}
  if(b.closest('#memoria')&&b.matches('[data-toast]')){navigate('/meu-passaporte');return;}
  if(b.dataset.toast)toast(b.dataset.toast);if(b.dataset.detail)toast(b.dataset.detail);
  if(b.matches('.start-card')){const filter=['natureza','gastronomia','cultura'][all('.start-card').indexOf(b)];const chosen=one(`.interest-filters [data-filter="${filter}"]`);if(chosen){select('.interest-filters button',chosen);all('#interest-grid article').forEach(c=>{c.hidden=c.dataset.category!==filter;});}}
  if(b.dataset.scroll)scroll(one(b.dataset.scroll));
  if(b.matches('.route-stop')){select('.route-stop',b);const el=one('#route-caption');if(el)el.textContent=b.dataset.route||'';}
  if(b.dataset.routeTab){select('[data-route-tab]',b,'aria-selected');all('[data-route-panel]').forEach(p=>{const active=p.dataset.routePanel===b.dataset.routeTab;p.classList.toggle('is-active',active);p.hidden=!active;});}
  if(b.matches('.interest-filters button')){select('.interest-filters button',b);all('#interest-grid article').forEach(c=>{c.hidden=b.dataset.filter!=='all'&&c.dataset.category!==b.dataset.filter;});}
  if(b.dataset.network){select('[data-network]',b);all('#network-grid article').forEach(c=>{c.hidden=b.dataset.network!=='all'&&c.dataset.kind!==b.dataset.network;});}
  if(b.dataset.tab){select('[data-tab]',b);all('[data-panel]').forEach(p=>{const active=p.dataset.panel===b.dataset.tab;p.classList.toggle('active',active);p.hidden=!active;});}
  if(b.dataset.signal){select('[data-signal]',b);const title=one('#signal-title'),copy=one('#signal-copy');if(title)title.textContent=b.dataset.signal;const messages:Record<string,string>={Descoberta:'Visualizações e origens de descoberta. Exemplo ilustrativo, sem resultados reais.',Intenção:'Inclusões em roteiro e sinais de interesse ligados ao negócio.',Presença:'Visitas registradas por evidência, sem confundir registro com compra.',Evolução:'Leitura de séries temporais quando houver volume suficiente para comparação.'};if(copy)copy.textContent=messages[b.dataset.signal];const index=all('[data-signal]').indexOf(b);all('#mock-chart i').forEach((bar,i)=>bar.style.setProperty('--h',`${24+((i*17+index*23)%68)}%`));}
  if(b.dataset.stage){select('[data-stage]',b);const el=one('#stage-status');if(el)el.textContent=`Etapa ${all('[data-stage]').indexOf(b)+1}: ${b.dataset.stage}. A evolução depende de sinais e operação consistentes.`;}
  if(b.matches('.pin')){select('.pin',b);const el=one('#territory-status');if(el)el.textContent=`Ponto selecionado: ${b.dataset.place}.`;}
  if(b.matches('.faq-list button')){const open=b.getAttribute('aria-expanded')==='true';all('.faq-list button').forEach(item=>{const expanded=item===b&&!open;item.setAttribute('aria-expanded',String(expanded));const answer=item.closest('article')?.querySelector<HTMLElement>('p');if(answer)answer.hidden=!expanded;});}
  if(b.matches('[data-open-contact]'))one<HTMLDialogElement>('#contact-modal')?.showModal();
  if(b.matches('[data-close-contact]'))one<HTMLDialogElement>('#contact-modal')?.close();
  if(b.id==='context-demo'){all('#context-cards article').forEach((c,i)=>later(()=>{c.classList.add('flash');later(()=>c.classList.remove('flash'),900);},i*180));toast('Chuva prevista: considere uma experiência coberta no seu roteiro.');}
 });
 all('[data-route-panel]').forEach(p=>{p.hidden=!p.classList.contains('is-active');p.setAttribute('role','tabpanel');});
 all('[data-route-tab]').forEach((tab,index)=>{const panel=one(`[data-route-panel="${index}"]`);tab.id=`route-tab-${index}`;tab.setAttribute('aria-controls',`route-panel-${index}`);if(panel){panel.id=`route-panel-${index}`;panel.setAttribute('aria-labelledby',tab.id);}});
 listen(one('.route-tabs'),'keydown',event=>{const key=(event as KeyboardEvent).key;const tabs=all('[data-route-tab]');const index=tabs.indexOf(event.target as HTMLElement);if(index<0||!['ArrowLeft','ArrowRight','Home','End'].includes(key))return;event.preventDefault();const next=key==='Home'?0:key==='End'?tabs.length-1:(index+(key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].click();tabs[next].focus();});
 all('[data-panel]').forEach(p=>{p.hidden=!p.classList.contains('active');});
 all('.faq-list button').forEach((b,i)=>{const answer=b.closest('article')?.querySelector<HTMLElement>('p');if(answer){answer.id=`reference-answer-${i}`;answer.hidden=true;b.setAttribute('aria-controls',answer.id);}});
 listen(one('#contact-form'),'submit',e=>{e.preventDefault();one<HTMLDialogElement>('#contact-modal')?.close();toast('Demonstração concluída. Nenhum dado foi enviado.');(e.target as HTMLFormElement).reset();});
 listen(one('#hero-search'),'submit',e=>{e.preventDefault();const value=one<HTMLInputElement>('#hero-query')?.value.trim();if(value)navigate(`/explorar?q=${encodeURIComponent(value)}`);else{toast('Digite um lugar ou uma experiência para buscar.');one('#hero-query')?.focus();}});
 const cards=all('.meet-card'),dots=one('.carousel-dots');let active=0,dragStart:number|null=null;
 function renderCarousel(){cards.forEach((c,i)=>{let d=(i-active+cards.length)%cards.length;if(d>cards.length/2)d-=cards.length;const a=Math.abs(d),x=d*Math.max(220,Math.min(root.clientWidth*.26,390));c.style.setProperty('transform',`translateX(calc(-50% + ${x}px)) translateY(${a*18}px) scale(${1-a*.08}) rotate(${d*-2.2}deg)`,'important');c.style.setProperty('opacity',String(Math.max(.18,1-a*.24)),'important');c.style.setProperty('filter',`blur(${a>1?(a-1)*2:0}px)`,'important');c.style.setProperty('z-index',String(20-a),'important');c.setAttribute('aria-hidden',String(a!==0));c.inert=a!==0;});all('.carousel-dots button').forEach((b,i)=>{b.classList.toggle('active',i===active);b.setAttribute('aria-pressed',String(i===active));});}
 const move=(n:number)=>{active=(active+n+cards.length)%cards.length;renderCarousel();};
 if(cards.length&&dots){dots.replaceChildren();cards.forEach((_,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',`Mostrar experiência ${i+1}`);listen(b,'click',()=>{active=i;renderCarousel();});dots.append(b);});listen(one('.carousel-arrow.prev'),'click',()=>move(-1));listen(one('.carousel-arrow.next'),'click',()=>move(1));listen(one('.carousel-stage'),'keydown',e=>{const key=(e as KeyboardEvent).key;if(key==='ArrowLeft'||key==='ArrowRight'){e.preventDefault();move(key==='ArrowRight'?1:-1);}});listen(one('.carousel-stage'),'pointerdown',e=>{dragStart=(e as PointerEvent).clientX;});listen(one('.carousel-stage'),'pointerup',e=>{if(dragStart!==null){const delta=(e as PointerEvent).clientX-dragStart;if(Math.abs(delta)>45)move(delta<0?1:-1);dragStart=null;}});listen(window,'resize',renderCarousel);renderCarousel();}
 if(kind==='place'){
  const choices:Record<string,{title:string;tag:string;text:string;image:string;alt:string}>={origem:{title:'Uma história em cada grão.',tag:'Conhecer quem faz',text:'Imagine uma conversa sobre o caminho do café, da produção à xícara. O conteúdo e o formato dependem da programação do local.',image:'cafe.webp',alt:'Conversa ilustrativa em um cafezal'},sabores:{title:'Descobertas que ficam na memória.',tag:'Explorar novos sabores',text:'Uma possibilidade de experiência gastronômica com produtos locais. Cardápio, valores e disponibilidade precisam ser confirmados com o ponto.',image:'sabores.webp',alt:'Preparação gastronômica ilustrativa'},encontro:{title:'O melhor ingrediente é a conversa.',tag:'Compartilhar o momento',text:'Uma pausa para estar junto e conhecer histórias locais. A atividade apresentada é ilustrativa, não uma oferta disponível para reserva.',image:'experiencia.webp',alt:'Experiência local ilustrativa'}};
  all('[data-choice]').forEach(b=>listen(b,'click',()=>{const c=choices[b.dataset.choice!];select('[data-choice]',b);for(const [id,value]of[['experience-title',c.title],['experience-tag',c.tag],['experience-text',c.text]]){const el=one(`#${id}`);if(el)el.textContent=value;}const img=one<HTMLImageElement>('#experience-image');if(img){img.src=`/reference-assets/place/${c.image}`;img.alt=c.alt;}}));
  const form=one<HTMLFormElement>('#plan-form'),result=one('#result'),date=one<HTMLInputElement>('input[name=data]');const today=new Date();if(date)date.min=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;let plan='';
  listen(form,'submit',e=>{e.preventDefault();if(!form||!result||!date||!form.reportValidity())return;const values=new FormData(form),formatted=new Date(date.value+'T12:00:00').toLocaleDateString('pt-BR'),summary=`${formatted} · ${values.get('pessoas')} · ${values.get('interesse')}`;plan=`Caminho do Café (ponto fictício)\n${summary}\n\nPLANO DEMONSTRATIVO, NÃO É RESERVA.\nConfirme endereço, horário, valores e disponibilidade antes de visitar.\nNenhum dado foi enviado.`;const el=one('#plan-summary');if(el)el.textContent=summary;form.hidden=true;result.hidden=false;result.focus();});
  listen(one('#edit-plan'),'click',()=>{if(form&&result){result.hidden=true;form.hidden=false;date?.focus();}});
  listen(one('#download-plan'),'click',()=>{const url=URL.createObjectURL(new Blob([plan],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='meu-plano-demonstrativo.txt';a.click();later(()=>URL.revokeObjectURL(url),1000);});
 }
 return()=>{controller.abort();timers.forEach(clearTimeout);clearTimeout(toastTimer);};
}
