import {aggregatePrivacyMinCount} from '@/core/privacy/config';
import {and,desc,eq} from 'drizzle-orm';
import {db} from '@/core/db';import {audit,partnerRequests,partners,places,placeMedia,trackingEvents,tripItems,visits} from '@/core/db/schema';import {sanitizeHttpsUrl,sanitizeInstagram,sanitizeNarrative,sanitizePhone,sanitizeText,sanitizeWhatsApp} from '@/core/security/sanitize';import type {Actor} from '@/core/auth/permissions';

const responseTimes=new Set(['within_1_hour','within_few_hours','same_day','one_business_day']);
export async function partnerContext(actor:Actor){if(actor.role!=='partner'||!actor.partnerId)throw new Error('Acesso de parceiro necessário.');const database=await db();const [partner]=await database.select().from(partners).where(and(eq(partners.id,actor.partnerId),eq(partners.status,'active')));if(!partner)throw new Error('Parceiro indisponível.');const [place]=await database.select().from(places).where(eq(places.id,partner.placeId));if(!place)throw new Error('Local do parceiro indisponível.');const [media]=await database.select().from(placeMedia).where(and(eq(placeMedia.placeId,place.id),eq(placeMedia.kind,'cover')));return{partner,place,media};}
function optionalUrl(value:unknown){return sanitizeHttpsUrl(value);}
export async function updatePartnerEditable(actor:Actor,form:FormData){
  const database=await db();const ctx=await partnerContext(actor);
  const openingHoursText=sanitizeText(form.get('openingHoursText'),1000)||null;const imageSrc=sanitizeText(form.get('imageSrc'),2048,{multiline:false});
  const responseTime=sanitizeText(form.get('responseTime'),100,{multiline:false});if(responseTime&&!responseTimes.has(responseTime))throw new Error('Tempo de resposta inválido.');
  const whatsapp=sanitizeWhatsApp(form.get('whatsapp'));const phone=sanitizePhone(form.get('phone'));const instagram=sanitizeInstagram(form.get('instagram'));const website=optionalUrl(form.get('website'));const bookingUrl=optionalUrl(form.get('bookingUrl'));const cover=imageSrc?optionalUrl(imageSrc):null;
  await database.transaction(async tx=>{
    const partnerUpdated=await tx.update(partners).set({whatsapp,phone,instagram,website,bookingUrl,responseTime:responseTime||null,version:ctx.partner.version+1}).where(and(eq(partners.id,ctx.partner.id),eq(partners.version,ctx.partner.version))).returning();if(!partnerUpdated.length)throw new Error('Os dados do parceiro mudaram. Atualize a página antes de salvar novamente.');
    const placeUpdated=await tx.update(places).set({openingHoursText,openingHoursType:openingHoursText?'partner_declared':null,version:ctx.place.version+1,updatedAt:new Date()}).where(and(eq(places.id,ctx.place.id),eq(places.version,ctx.place.version))).returning();if(!placeUpdated.length)throw new Error('Os dados do local mudaram. Atualize a página antes de salvar novamente.');
    if(cover){if(ctx.media)await tx.update(placeMedia).set({src:cover,illustrative:false,notActualPlace:false,status:'published'}).where(eq(placeMedia.id,ctx.media.id));else await tx.insert(placeMedia).values({id:crypto.randomUUID(),placeId:ctx.place.id,kind:'cover',src:cover,alt:`Imagem de ${sanitizeText(ctx.place.name,500)}`,status:'published'});}
    await tx.insert(audit).values({id:crypto.randomUUID(),actor:actor.id,action:'partner_direct_edit',entity:ctx.partner.id,before:{partnerVersion:ctx.partner.version,placeVersion:ctx.place.version},after:{partnerVersion:ctx.partner.version+1,placeVersion:ctx.place.version+1,editableFields:['contacts','responseTime','openingHours','coverImage']}});
  });
}
export async function createPartnerRequest(actor:Actor,form:FormData){const ctx=await partnerContext(actor);const requestType=sanitizeText(form.get('requestType'),100,{multiline:false});if(!['identity','category','experience','section','structural_removal','structural_information'].includes(requestType))throw new Error('Tipo de solicitação inválido.');const details=sanitizeNarrative(form.get('details'),5000);if(Array.from(details).length<10)throw new Error('Descreva a solicitação com mais detalhes.');const database=await db();await database.insert(partnerRequests).values({id:crypto.randomUUID(),partnerId:ctx.partner.id,requesterId:actor.id,requestType,status:'pending',requestedChanges:{details}});}
export async function partnerRequestsFor(actor:Actor){const ctx=await partnerContext(actor);return (await db()).select().from(partnerRequests).where(eq(partnerRequests.partnerId,ctx.partner.id)).orderBy(desc(partnerRequests.createdAt));}
export async function partnerAnalytics(actor:Actor){const ctx=await partnerContext(actor);const database=await db();const events=await database.select().from(trackingEvents);const own=events.filter(e=>e.partnerId===ctx.partner.id||e.placeId===ctx.place.id||String(e.payload?.placeId||'')===ctx.place.id);const visitRows=await database.select().from(visits).where(eq(visits.placeId,ctx.place.id));const allItems=await database.select().from(tripItems).where(eq(tripItems.placeId,ctx.place.id));const planned=allItems.filter(i=>i.state!=='removed').length;const counts=(event:string)=>own.filter(e=>e.event===event).length;return{place:ctx.place,partner:ctx.partner,views:counts('PLACE_VIEWED')+counts('PARTNER_CARD_CLICK'),externalClicks:counts('CONTACT_CLICKED')+counts('WHATSAPP_CLICKED')+counts('PHONE_CLICKED')+counts('WEBSITE_CLICKED')+counts('EXTERNAL_BOOKING_CLICKED'),planned,visits:visitRows.length,returns:visitRows.filter(v=>v.visitNumber>1).length,origins:Object.entries(own.reduce<Record<string,number>>((acc,e)=>{const source=sanitizeText(e.payload?.source||'direto',64,{multiline:false})||'direto';acc[source]=(acc[source]||0)+1;return acc},{})).filter(([,count])=>count>=aggregatePrivacyMinCount()).sort((a,b)=>b[1]-a[1]).slice(0,5)};}
