/* eslint-disable */
// Lucide v1.31.0, ISC license in docs/LUCIDE_LICENSE.txt. Generated by scripts/build-icons.mjs.
import type {IconDefinition} from './types';
export const builtinIcons:IconDefinition[]=[
  {
    "id": "coffee",
    "label": "Café",
    "svg": "<path d=\"M10 2v2\"/><path d=\"M14 2v2\"/><path d=\"M16 8a1 1 0 0 1 1 1v8a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1h14a4 4 0 1 1 0 8h-1\"/><path d=\"M6 2v2\"/>",
    "aliases": [
      "cafeteria",
      "cafe",
      "café",
      "coffee-shop",
      "coffee-roaster",
      "coffee-farm",
      "coffee-tasting",
      "specialty-coffee",
      "coffee",
      "torrefacao"
    ]
  },
  {
    "id": "grape",
    "label": "Vinícola",
    "svg": "<path d=\"M22 5V2l-5.89 5.89\"/><circle cx=\"16.6\" cy=\"15.89\" r=\"3\"/><circle cx=\"8.11\" cy=\"7.4\" r=\"3\"/><circle cx=\"12.35\" cy=\"11.65\" r=\"3\"/><circle cx=\"13.91\" cy=\"5.85\" r=\"3\"/><circle cx=\"18.15\" cy=\"10.09\" r=\"3\"/><circle cx=\"6.56\" cy=\"13.2\" r=\"3\"/><circle cx=\"10.8\" cy=\"17.44\" r=\"3\"/><circle cx=\"5\" cy=\"19\" r=\"3\"/>",
    "aliases": [
      "vinicola",
      "vinícola",
      "vinho",
      "wine",
      "winery",
      "vineyard",
      "wine-tasting",
      "uva"
    ]
  },
  {
    "id": "beer",
    "label": "Cervejaria",
    "svg": "<path d=\"M17 11h1a3 3 0 0 1 0 6h-1\"/><path d=\"M9 12v6\"/><path d=\"M13 12v6\"/><path d=\"M14 7.5c-1 0-1.44.5-3 .5s-2-.5-3-.5-1.72.5-2.5.5a2.5 2.5 0 0 1 0-5c.78 0 1.57.5 2.5.5S9.44 2 11 2s2 1.5 3 1.5 1.72-.5 2.5-.5a2.5 2.5 0 0 1 0 5c-.78 0-1.5-.5-2.5-.5Z\"/><path d=\"M5 8v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V8\"/>",
    "aliases": [
      "cervejaria",
      "cerveja",
      "beer",
      "brewery",
      "craft-beer",
      "beer-tasting"
    ]
  },
  {
    "id": "utensils",
    "label": "Restaurante",
    "svg": "<path d=\"M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2\"/><path d=\"M7 2v20\"/><path d=\"M21 15V2a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3Zm0 0v7\"/>",
    "aliases": [
      "restaurante",
      "restaurant",
      "restaurant-general",
      "italian-food",
      "regional-food",
      "brazilian-food",
      "buffet",
      "gourmet",
      "farm-to-table",
      "culinaria",
      "tasting",
      "cooking-class"
    ]
  },
  {
    "id": "croissant",
    "label": "Padaria",
    "svg": "<path d=\"M10.2 18H4.774a1.5 1.5 0 0 1-1.352-.97 11 11 0 0 1 .132-6.487\"/><path d=\"M18 10.2V4.774a1.5 1.5 0 0 0-.97-1.352 11 11 0 0 0-6.486.132\"/><path d=\"M18 5a4 3 0 0 1 4 3 2 2 0 0 1-2 2 10 10 0 0 0-5.139 1.42\"/><path d=\"M5 18a3 4 0 0 0 3 4 2 2 0 0 0 2-2 10 10 0 0 1 1.42-5.14\"/><path d=\"M8.709 2.554a10 10 0 0 0-6.155 6.155 1.5 1.5 0 0 0 .676 1.626l9.807 5.42a2 2 0 0 0 2.718-2.718l-5.42-9.807a1.5 1.5 0 0 0-1.626-.676\"/>",
    "aliases": [
      "padaria",
      "bakery",
      "breakfast",
      "brunch"
    ]
  },
  {
    "id": "cake-slice",
    "label": "Confeitaria",
    "svg": "<path d=\"M16 13H3\"/><path d=\"M16 17H3\"/><path d=\"m7.2 7.9-3.388 2.5A2 2 0 0 0 3 12.01V20a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-8.654c0-2-2.44-6.026-6.44-8.026a1 1 0 0 0-1.082.057L10.4 5.6\"/><circle cx=\"9\" cy=\"7\" r=\"2\"/>",
    "aliases": [
      "confeitaria",
      "confectionery",
      "dessert",
      "doceria"
    ]
  },
  {
    "id": "ice-cream-cone",
    "label": "Sorveteria",
    "svg": "<path d=\"m7 11 4.08 10.35a1 1 0 0 0 1.84 0L17 11\"/><path d=\"M17 7A5 5 0 0 0 7 7\"/><path d=\"M17 7a2 2 0 0 1 0 4H7a2 2 0 0 1 0-4\"/>",
    "aliases": [
      "sorveteria",
      "ice-cream"
    ]
  },
  {
    "id": "candy",
    "label": "Chocolateria",
    "svg": "<path d=\"M10 7v10.9\"/><path d=\"M14 6.1V17\"/><path d=\"M16 7V3a1 1 0 0 1 1.707-.707 2.5 2.5 0 0 0 2.152.717 1 1 0 0 1 1.131 1.131 2.5 2.5 0 0 0 .717 2.152A1 1 0 0 1 21 8h-4\"/><path d=\"M16.536 7.465a5 5 0 0 0-7.072 0l-2 2a5 5 0 0 0 0 7.07 5 5 0 0 0 7.072 0l2-2a5 5 0 0 0 0-7.07\"/><path d=\"M8 17v4a1 1 0 0 1-1.707.707 2.5 2.5 0 0 0-2.152-.717 1 1 0 0 1-1.131-1.131 2.5 2.5 0 0 0-.717-2.152A1 1 0 0 1 3 16h4\"/>",
    "aliases": [
      "chocolate",
      "chocolateria"
    ]
  },
  {
    "id": "pizza",
    "label": "Pizzaria",
    "svg": "<path d=\"m12 14-1 1\"/><path d=\"m13.75 18.25-1.25 1.42\"/><path d=\"M17.775 5.654a15.68 15.68 0 0 0-12.121 12.12\"/><path d=\"M18.8 9.3a1 1 0 0 0 2.1 7.7\"/><path d=\"M21.964 20.732a1 1 0 0 1-1.232 1.232l-18-5a1 1 0 0 1-.695-1.232A19.68 19.68 0 0 1 15.732 2.037a1 1 0 0 1 1.232.695z\"/>",
    "aliases": [
      "pizza",
      "pizzaria"
    ]
  },
  {
    "id": "sandwich",
    "label": "Lanches",
    "svg": "<path d=\"m2.37 11.223 8.372-6.777a2 2 0 0 1 2.516 0l8.371 6.777\"/><path d=\"M21 15a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-5.25\"/><path d=\"M3 15a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h9\"/><path d=\"m6.67 15 6.13 4.6a2 2 0 0 0 2.8-.4l3.15-4.2\"/><rect width=\"20\" height=\"4\" x=\"2\" y=\"11\" rx=\"1\"/>",
    "aliases": [
      "burger",
      "hamburgueria",
      "street-food",
      "lanchonete"
    ]
  },
  {
    "id": "beef",
    "label": "Churrascaria",
    "svg": "<path d=\"M16.4 13.7A6.5 6.5 0 1 0 6.28 6.6c-1.1 3.13-.78 3.9-3.18 6.08A3 3 0 0 0 5 18c4 0 8.4-1.8 11.4-4.3\"/><path d=\"m18.5 6 2.19 4.5a6.48 6.48 0 0 1-2.29 7.2C15.4 20.2 11 22 7 22a3 3 0 0 1-2.68-1.66L2.4 16.5\"/><circle cx=\"12.5\" cy=\"8.5\" r=\"2.5\"/>",
    "aliases": [
      "barbecue",
      "steakhouse",
      "churrascaria",
      "defumados"
    ]
  },
  {
    "id": "fish",
    "label": "Peixes e pesca",
    "svg": "<path d=\"M6.5 12c.94-3.46 4.94-6 8.5-6 3.56 0 6.06 2.54 7 6-.94 3.47-3.44 6-7 6s-7.56-2.53-8.5-6Z\"/><path d=\"M18 12v.5\"/><path d=\"M16 17.93a9.77 9.77 0 0 1 0-11.86\"/><path d=\"M7 10.67C7 8 5.58 5.97 2.73 5.5c-1 1.5-1 5 .23 6.5-1.24 1.5-1.24 5-.23 6.5C5.58 18.03 7 16 7 13.33\"/><path d=\"M10.46 7.26C10.2 5.88 9.17 4.24 8 3h5.8a2 2 0 0 1 1.98 1.67l.23 1.4\"/><path d=\"m16.01 17.93-.23 1.4A2 2 0 0 1 13.8 21H9.5a5.96 5.96 0 0 0 1.49-3.98\"/>",
    "aliases": [
      "japanese-food",
      "asian-food",
      "fishing",
      "pesca",
      "pescaria"
    ]
  },
  {
    "id": "leaf",
    "label": "Vegetariano",
    "svg": "<path d=\"M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z\"/><path d=\"M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12\"/>",
    "aliases": [
      "vegan",
      "vegetarian",
      "vegetariano",
      "vegano"
    ]
  },
  {
    "id": "truck",
    "label": "Food truck",
    "svg": "<path d=\"M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2\"/><path d=\"M15 18H9\"/><path d=\"M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14\"/><circle cx=\"17\" cy=\"18\" r=\"2\"/><circle cx=\"7\" cy=\"18\" r=\"2\"/>",
    "aliases": [
      "food-truck"
    ]
  },
  {
    "id": "wine",
    "label": "Destilaria e bar",
    "svg": "<path d=\"M8 22h8\"/><path d=\"M7 10h10\"/><path d=\"M12 15v7\"/><path d=\"M12 15a5 5 0 0 0 5-5c0-2-.5-4-2-8H9c-1.5 4-2 6-2 8a5 5 0 0 0 5 5Z\"/>",
    "aliases": [
      "distillery",
      "cachaca",
      "cachaça",
      "cocktail",
      "bar"
    ]
  },
  {
    "id": "cup-soda",
    "label": "Sucos",
    "svg": "<path d=\"m6 8 1.75 12.28a2 2 0 0 0 2 1.72h4.54a2 2 0 0 0 2-1.72L18 8\"/><path d=\"M5 8h14\"/><path d=\"M7 15a6.47 6.47 0 0 1 5 0 6.47 6.47 0 0 0 5 0\"/><path d=\"m12 8 1-6h2\"/>",
    "aliases": [
      "juice",
      "suco",
      "sucos"
    ]
  },
  {
    "id": "tea",
    "label": "Chá",
    "svg": "<path d=\"m6 8 1.75 12.28a2 2 0 0 0 2 1.72h4.54a2 2 0 0 0 2-1.72L18 8\"/><path d=\"M5 8h14\"/><path d=\"M7 15a6.47 6.47 0 0 1 5 0 6.47 6.47 0 0 0 5 0\"/><path d=\"m12 8 1-6h2\"/>",
    "aliases": [
      "tea",
      "cha",
      "chá"
    ]
  },
  {
    "id": "bed-double",
    "label": "Pousada",
    "svg": "<path d=\"M2 20v-8a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v8\"/><path d=\"M4 10V6a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v4\"/><path d=\"M12 4v6\"/><path d=\"M2 18h20\"/>",
    "aliases": [
      "inn",
      "pousada",
      "hostel",
      "hospedagem",
      "guest-house"
    ]
  },
  {
    "id": "hotel",
    "label": "Hotel",
    "svg": "<path d=\"M10 22v-6.57\"/><path d=\"M12 11h.01\"/><path d=\"M12 7h.01\"/><path d=\"M14 15.43V22\"/><path d=\"M15 16a5 5 0 0 0-6 0\"/><path d=\"M16 11h.01\"/><path d=\"M16 7h.01\"/><path d=\"M8 11h.01\"/><path d=\"M8 7h.01\"/><rect x=\"4\" y=\"2\" width=\"16\" height=\"20\" rx=\"2\"/>",
    "aliases": [
      "hotel",
      "resort",
      "spa-hotel"
    ]
  },
  {
    "id": "tent",
    "label": "Camping",
    "svg": "<path d=\"M3.5 21 14 3\"/><path d=\"M20.5 21 10 3\"/><path d=\"M15.5 21 12 15l-3.5 6\"/><path d=\"M2 21h20\"/>",
    "aliases": [
      "camping",
      "glamping"
    ]
  },
  {
    "id": "house",
    "label": "Chalé",
    "svg": "<path d=\"M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8\"/><path d=\"M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\"/>",
    "aliases": [
      "chalet",
      "cabin",
      "chale",
      "cabana",
      "rental",
      "vacation-rental",
      "eco-lodge"
    ]
  },
  {
    "id": "trees",
    "label": "Parque e floresta",
    "svg": "<path d=\"M10 10v.2A3 3 0 0 1 8.9 16H5a3 3 0 0 1-1-5.8V10a3 3 0 0 1 6 0Z\"/><path d=\"M7 16v6\"/><path d=\"M13 19v3\"/><path d=\"M12 19h8.3a1 1 0 0 0 .7-1.7L18 14h.3a1 1 0 0 0 .7-1.7L16 9h.2a1 1 0 0 0 .8-1.7L13 3l-1.4 1.5\"/>",
    "aliases": [
      "park",
      "forest",
      "parque",
      "floresta",
      "ecopark",
      "bioparque",
      "nature-reserve",
      "family-park",
      "pet-park"
    ]
  },
  {
    "id": "waves",
    "label": "Rios e lagos",
    "svg": "<path d=\"M2 12q2.5 2 5 0t5 0 5 0 5 0\"/><path d=\"M2 19q2.5 2 5 0t5 0 5 0 5 0\"/><path d=\"M2 5q2.5 2 5 0t5 0 5 0 5 0\"/>",
    "aliases": [
      "river",
      "lake",
      "rio",
      "lago",
      "spring",
      "water"
    ]
  },
  {
    "id": "mountain",
    "label": "Montanha",
    "svg": "<path d=\"m8 3 4 8 5-5 5 15H2L8 3z\"/>",
    "aliases": [
      "mountain",
      "hill",
      "montanha",
      "serra",
      "valley",
      "rock",
      "cave",
      "viewpoint",
      "landscape",
      "panorama",
      "aventureiro"
    ]
  },
  {
    "id": "flower-2",
    "label": "Jardim",
    "svg": "<path d=\"M12 5a3 3 0 1 1 3 3m-3-3a3 3 0 1 0-3 3m3-3v1M9 8a3 3 0 1 0 3 3M9 8h1m5 0a3 3 0 1 1-3 3m3-3h-1m-2 3v-1\"/><circle cx=\"12\" cy=\"8\" r=\"2\"/><path d=\"M12 10v12\"/><path d=\"M12 22c4.2 0 7-1.667 7-5-4.2 0-7 1.667-7 5Z\"/><path d=\"M12 22c-4.2 0-7-1.667-7-5 4.2 0 7 1.667 7 5Z\"/>",
    "aliases": [
      "garden",
      "botanical-garden",
      "jardim",
      "flowers",
      "floricultura"
    ]
  },
  {
    "id": "footprints",
    "label": "Trilha",
    "svg": "<path d=\"M4 16v-2.38C4 11.5 2.97 10.5 3 8c.03-2.72 1.49-6 4.5-6C9.37 2 10 3.8 10 5.5c0 3.11-2 5.66-2 8.68V16a2 2 0 1 1-4 0Z\"/><path d=\"M20 20v-2.38c0-2.12 1.03-3.12 1-5.62-.03-2.72-1.49-6-4.5-6C14.63 6 14 7.8 14 9.5c0 3.11 2 5.66 2 8.68V20a2 2 0 1 0 4 0Z\"/><path d=\"M16 17h4\"/><path d=\"M4 13h4\"/>",
    "aliases": [
      "hiking",
      "trail",
      "trekking",
      "trilha",
      "walking-tour"
    ]
  },
  {
    "id": "bike",
    "label": "Ciclismo",
    "svg": "<circle cx=\"18.5\" cy=\"17.5\" r=\"3.5\"/><circle cx=\"5.5\" cy=\"17.5\" r=\"3.5\"/><circle cx=\"15\" cy=\"5\" r=\"1\"/><path d=\"M12 17.5V14l-3-3 4-3 2 3h2\"/>",
    "aliases": [
      "cycling",
      "mountain-bike",
      "bike",
      "ciclismo",
      "bike-parking"
    ]
  },
  {
    "id": "car-front",
    "label": "Passeio de jipe",
    "svg": "<path d=\"m21 8-2 2-1.5-3.7A2 2 0 0 0 15.646 5H8.4a2 2 0 0 0-1.903 1.257L5 10 3 8\"/><path d=\"M7 14h.01\"/><path d=\"M17 14h.01\"/><rect width=\"18\" height=\"8\" x=\"3\" y=\"10\" rx=\"2\"/><path d=\"M5 18v2\"/><path d=\"M19 18v2\"/>",
    "aliases": [
      "off-road",
      "jeep-tour",
      "jeep",
      "car",
      "4x4"
    ]
  },
  {
    "id": "sailboat",
    "label": "Navegação",
    "svg": "<path d=\"M10 2v15\"/><path d=\"M7 22a4 4 0 0 1-4-4 1 1 0 0 1 1-1h16a1 1 0 0 1 1 1 4 4 0 0 1-4 4z\"/><path d=\"M9.159 2.46a1 1 0 0 1 1.521-.193l9.977 8.98A1 1 0 0 1 20 13H4a1 1 0 0 1-.824-1.567z\"/>",
    "aliases": [
      "rafting",
      "kayak",
      "canoe",
      "boat",
      "barco",
      "caiaque"
    ]
  },
  {
    "id": "wind",
    "label": "Voo livre",
    "svg": "<path d=\"M12.8 19.6A2 2 0 1 0 14 16H2\"/><path d=\"M17.5 8a2.5 2.5 0 1 1 2 4H2\"/><path d=\"M9.8 4.4A2 2 0 1 1 11 8H2\"/>",
    "aliases": [
      "paragliding",
      "hang-gliding",
      "voo-livre"
    ]
  },
  {
    "id": "mountain-snow",
    "label": "Aventura",
    "svg": "<path d=\"m8 3 4 8 5-5 5 15H2L8 3z\"/><path d=\"M4.14 15.08c2.62-1.57 5.24-1.43 7.86.42 2.74 1.94 5.49 2 8.23.19\"/>",
    "aliases": [
      "climbing",
      "zipline",
      "rappel",
      "adventure-park",
      "aventura",
      "tirolesa",
      "escalada"
    ]
  },
  {
    "id": "landmark",
    "label": "Museu e patrimônio",
    "svg": "<path d=\"M10 18v-7\"/><path d=\"M11.119 2.205a2 2 0 0 1 1.762 0l7.84 3.846A.5.5 0 0 1 20.5 7h-17a.5.5 0 0 1-.22-.949z\"/><path d=\"M14 18v-7\"/><path d=\"M18 18v-7\"/><path d=\"M3 22h18\"/><path d=\"M6 18v-7\"/>",
    "aliases": [
      "museum",
      "museu",
      "historic-building",
      "heritage",
      "monument",
      "memorial",
      "cultural-center",
      "traditional-culture",
      "local-history",
      "historic",
      "architecture",
      "old-town",
      "heritage-route",
      "historic-route"
    ]
  },
  {
    "id": "palette",
    "label": "Arte",
    "svg": "<path d=\"M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z\"/><circle cx=\"13.5\" cy=\"6.5\" r=\".5\" fill=\"currentColor\"/><circle cx=\"17.5\" cy=\"10.5\" r=\".5\" fill=\"currentColor\"/><circle cx=\"6.5\" cy=\"12.5\" r=\".5\" fill=\"currentColor\"/><circle cx=\"8.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\"/>",
    "aliases": [
      "gallery",
      "art",
      "exhibition",
      "galeria",
      "arte"
    ]
  },
  {
    "id": "drama",
    "label": "Teatro",
    "svg": "<path d=\"M10 11h.01\"/><path d=\"M14 6h.01\"/><path d=\"M18 6h.01\"/><path d=\"M6.5 13.1h.01\"/><path d=\"M22 5c0 9-4 12-6 12s-6-3-6-12c0-2 2-3 6-3s6 1 6 3\"/><path d=\"M17.4 9.9c-.8.8-2 .8-2.8 0\"/><path d=\"M10.1 7.1C9 7.2 7.7 7.7 6 8.6c-3.5 2-4.7 3.9-3.7 5.6 4.5 7.8 9.5 8.4 11.2 7.4.9-.5 1.9-2.1 1.9-4.7\"/><path d=\"M9.1 16.5c.3-1.1 1.4-1.7 2.4-1.4\"/>",
    "aliases": [
      "theater",
      "teatro"
    ]
  },
  {
    "id": "clapperboard",
    "label": "Cinema",
    "svg": "<path d=\"m12.296 3.464 3.02 3.956\"/><path d=\"M20.2 6 3 11l-.9-2.4c-.3-1.1.3-2.2 1.3-2.5l13.5-4c1.1-.3 2.2.3 2.5 1.3z\"/><path d=\"M3 11h18v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\"/><path d=\"m6.18 5.276 3.1 3.899\"/>",
    "aliases": [
      "cinema"
    ]
  },
  {
    "id": "book-open",
    "label": "Biblioteca",
    "svg": "<path d=\"M12 5v16\"/><path d=\"M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z\"/>",
    "aliases": [
      "library",
      "biblioteca",
      "educational"
    ]
  },
  {
    "id": "music",
    "label": "Música",
    "svg": "<path d=\"M9 18V5l12-2v13\"/><circle cx=\"6\" cy=\"18\" r=\"3\"/><circle cx=\"18\" cy=\"16\" r=\"3\"/>",
    "aliases": [
      "music",
      "musica",
      "show",
      "concert"
    ]
  },
  {
    "id": "church",
    "label": "Igreja",
    "svg": "<path d=\"M10 9h4\"/><path d=\"M12 7v5\"/><path d=\"M14 21v-3a2 2 0 0 0-4 0v3\"/><path d=\"m18 9 3.52 2.147a1 1 0 0 1 .48.854V19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-6.999a1 1 0 0 1 .48-.854L6 9\"/><path d=\"M6 21V7a1 1 0 0 1 .376-.782l5-3.999a1 1 0 0 1 1.249.001l5 4A1 1 0 0 1 18 7v14\"/>",
    "aliases": [
      "church",
      "chapel",
      "cathedral",
      "basilica",
      "temple",
      "sanctuary",
      "monastery",
      "convent",
      "religious-tourism",
      "religious-monument",
      "igreja",
      "capela",
      "catedral",
      "paroquia"
    ]
  },
  {
    "id": "tractor",
    "label": "Fazenda",
    "svg": "<path d=\"m10 11 11 .9a1 1 0 0 1 .8 1.1l-.665 4.158a1 1 0 0 1-.988.842H20\"/><path d=\"M16 18h-5\"/><path d=\"M18 5a1 1 0 0 0-1 1v5.573\"/><path d=\"M3 4h8.129a1 1 0 0 1 .99.863L13 11.246\"/><path d=\"M4 11V4\"/><path d=\"M7 15h.01\"/><path d=\"M8 10.1V4\"/><circle cx=\"18\" cy=\"18\" r=\"2\"/><circle cx=\"7\" cy=\"15\" r=\"5\"/>",
    "aliases": [
      "farm",
      "ranch",
      "farm-hotel",
      "fazenda",
      "agritourism",
      "rural-experience",
      "turismo-rural"
    ]
  },
  {
    "id": "milk",
    "label": "Laticínios",
    "svg": "<path d=\"M8 2h8\"/><path d=\"M9 2v2.789a4 4 0 0 1-.672 2.219l-.656.984A4 4 0 0 0 7 10.212V20a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2v-9.789a4 4 0 0 0-.672-2.219l-.656-.984A4 4 0 0 1 15 4.788V2\"/><path d=\"M7 15a6.472 6.472 0 0 1 5 0 6.47 6.47 0 0 0 5 0\"/>",
    "aliases": [
      "dairy",
      "cheese",
      "queijo",
      "queijaria",
      "laticinio"
    ]
  },
  {
    "id": "sprout",
    "label": "Cultivo",
    "svg": "<path d=\"M14 9.536V7a4 4 0 0 1 4-4h1.5a.5.5 0 0 1 .5.5V5a4 4 0 0 1-4 4 4 4 0 0 0-4 4c0 2 1 3 1 5a5 5 0 0 1-1 3\"/><path d=\"M4 9a5 5 0 0 1 8 4 5 5 0 0 1-8-4\"/><path d=\"M5 21h14\"/>",
    "aliases": [
      "organic-farm",
      "orchard",
      "plantation",
      "greenhouse",
      "horta",
      "pomar"
    ]
  },
  {
    "id": "hexagon",
    "label": "Mel e apicultura",
    "svg": "<path d=\"M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z\"/>",
    "aliases": [
      "honey",
      "apiary",
      "mel",
      "apicultura"
    ]
  },
  {
    "id": "shopping-bag",
    "label": "Loja e lembranças",
    "svg": "<path d=\"M16 10a4 4 0 0 1-8 0\"/><path d=\"M3.103 6.034h17.794\"/><path d=\"M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z\"/>",
    "aliases": [
      "store",
      "shopping",
      "souvenir",
      "local-products",
      "factory-store",
      "outlet",
      "loja",
      "lembrancas"
    ]
  },
  {
    "id": "shirt",
    "label": "Moda",
    "svg": "<path d=\"M20.38 3.46 16 2a4 4 0 0 1-8 0L3.62 3.46a2 2 0 0 0-1.34 2.23l.58 3.47a1 1 0 0 0 .99.84H6v10c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V10h2.15a1 1 0 0 0 .99-.84l.58-3.47a2 2 0 0 0-1.34-2.23z\"/>",
    "aliases": [
      "fashion",
      "clothing",
      "moda",
      "roupas"
    ]
  },
  {
    "id": "hammer",
    "label": "Artesanato",
    "svg": "<path d=\"m15 12-9.373 9.373a1 1 0 0 1-3.001-3L12 9\"/><path d=\"m18 15 4-4\"/><path d=\"m21.5 11.5-1.914-1.914A2 2 0 0 1 19 8.172v-.344a2 2 0 0 0-.586-1.414l-1.657-1.657A6 6 0 0 0 12.516 3H9l1.243 1.243A6 6 0 0 1 12 8.485V10l2 2h1.172a2 2 0 0 1 1.414.586L18.5 14.5\"/>",
    "aliases": [
      "crafts",
      "artesanato",
      "ceramics",
      "ceramica",
      "workshop"
    ]
  },
  {
    "id": "store",
    "label": "Mercado",
    "svg": "<path d=\"M15 21v-5a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v5\"/><path d=\"M17.774 10.31a1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.451 0 1.12 1.12 0 0 0-1.548 0 2.5 2.5 0 0 1-3.452 0 1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.77-3.248l2.889-4.184A2 2 0 0 1 7 2h10a2 2 0 0 1 1.653.873l2.895 4.192a2.5 2.5 0 0 1-3.774 3.244\"/><path d=\"M4 10.95V19a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8.05\"/>",
    "aliases": [
      "market",
      "street-market",
      "marketplace",
      "mercado",
      "feira"
    ]
  },
  {
    "id": "gem",
    "label": "Joalheria",
    "svg": "<path d=\"M10.5 3 8 9l4 13 4-13-2.5-6\"/><path d=\"M17 3a2 2 0 0 1 1.6.8l3 4a2 2 0 0 1 .013 2.382l-7.99 10.986a2 2 0 0 1-3.247 0l-7.99-10.986A2 2 0 0 1 2.4 7.8l2.998-3.997A2 2 0 0 1 7 3z\"/><path d=\"M2 9h20\"/>",
    "aliases": [
      "jewelry",
      "joia",
      "joalheria"
    ]
  },
  {
    "id": "armchair",
    "label": "Decoração",
    "svg": "<path d=\"M19 9V6a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v3\"/><path d=\"M3 16a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-5a2 2 0 0 0-4 0v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V11a2 2 0 0 0-4 0z\"/><path d=\"M5 18v2\"/><path d=\"M19 18v2\"/>",
    "aliases": [
      "decor",
      "antiques",
      "decoracao",
      "antiguidades"
    ]
  },
  {
    "id": "flower",
    "label": "Bem-estar",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"3\"/><path d=\"M12 16.5A4.5 4.5 0 1 1 7.5 12 4.5 4.5 0 1 1 12 7.5a4.5 4.5 0 1 1 4.5 4.5 4.5 4.5 0 1 1-4.5 4.5\"/><path d=\"M12 7.5V9\"/><path d=\"M7.5 12H9\"/><path d=\"M16.5 12H15\"/><path d=\"M12 16.5V15\"/><path d=\"m8 8 1.88 1.88\"/><path d=\"M14.12 9.88 16 8\"/><path d=\"m8 16 1.88-1.88\"/><path d=\"M14.12 14.12 16 16\"/>",
    "aliases": [
      "spa",
      "massage",
      "wellness",
      "yoga",
      "meditation",
      "beauty",
      "relaxation",
      "therapy",
      "massagem",
      "bem-estar"
    ]
  },
  {
    "id": "bath",
    "label": "Termas",
    "svg": "<path d=\"M10 4 8 6\"/><path d=\"M17 19v2\"/><path d=\"M2 12h20\"/><path d=\"M7 19v2\"/><path d=\"M9 5 7.621 3.621A2.121 2.121 0 0 0 4 5v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-5\"/>",
    "aliases": [
      "thermal-water",
      "hot-spring",
      "sauna",
      "termas",
      "banho"
    ]
  },
  {
    "id": "cable-car",
    "label": "Teleférico",
    "svg": "<path d=\"M10 3h.01\"/><path d=\"M14 2h.01\"/><path d=\"m2 9 20-5\"/><path d=\"M12 12V6.5\"/><rect width=\"16\" height=\"10\" x=\"4\" y=\"12\" rx=\"3\"/><path d=\"M9 12v5\"/><path d=\"M15 12v5\"/><path d=\"M4 17h16\"/>",
    "aliases": [
      "cable-car",
      "teleferico",
      "teleférico",
      "funicular"
    ]
  },
  {
    "id": "train-front",
    "label": "Trem turístico",
    "svg": "<path d=\"M8 3.1V7a4 4 0 0 0 8 0V3.1\"/><path d=\"m9 15-1-1\"/><path d=\"m15 15 1-1\"/><path d=\"M9 19c-2.8 0-5-2.2-5-5v-4a8 8 0 0 1 16 0v4c0 2.8-2.2 5-5 5Z\"/><path d=\"m8 19-2 3\"/><path d=\"m16 19 2 3\"/>",
    "aliases": [
      "train",
      "tourist-train",
      "tram",
      "railway",
      "trem"
    ]
  },
  {
    "id": "bus",
    "label": "Ônibus turístico",
    "svg": "<path d=\"M8 6v6\"/><path d=\"M15 6v6\"/><path d=\"M2 12h19.6\"/><path d=\"M18 18h3s.5-1.7.8-2.8c.1-.4.2-.8.2-1.2 0-.4-.1-.8-.2-1.2l-1.4-5C20.1 6.8 19.1 6 18 6H4a2 2 0 0 0-2 2v10h3\"/><circle cx=\"7\" cy=\"18\" r=\"2\"/><path d=\"M9 18h5\"/><circle cx=\"16\" cy=\"18\" r=\"2\"/>",
    "aliases": [
      "bus-tour",
      "transportation",
      "onibus"
    ]
  },
  {
    "id": "ferris-wheel",
    "label": "Parque de diversões",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"2\"/><path d=\"M12 2v4\"/><path d=\"m6.8 15-3.5 2\"/><path d=\"m20.7 7-3.5 2\"/><path d=\"M6.8 9 3.3 7\"/><path d=\"m20.7 17-3.5-2\"/><path d=\"m9 22 3-8 3 8\"/><path d=\"M8 22h8\"/><path d=\"M18 18.7a9 9 0 1 0-12 0\"/>",
    "aliases": [
      "theme-park",
      "amusement-park",
      "parque-de-diversoes"
    ]
  },
  {
    "id": "gamepad-2",
    "label": "Jogos",
    "svg": "<line x1=\"6\" x2=\"10\" y1=\"11\" y2=\"11\"/><line x1=\"8\" x2=\"8\" y1=\"9\" y2=\"13\"/><line x1=\"15\" x2=\"15.01\" y1=\"12\" y2=\"12\"/><line x1=\"18\" x2=\"18.01\" y1=\"10\" y2=\"10\"/><path d=\"M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.545-.604-6.584-.685-7.258-.007-.05-.011-.1-.017-.151A4 4 0 0 0 17.32 5z\"/>",
    "aliases": [
      "arcade",
      "games",
      "interactive-attraction",
      "interactive",
      "jogos"
    ]
  },
  {
    "id": "party-popper",
    "label": "Eventos",
    "svg": "<path d=\"M5.8 11.3 2 22l10.7-3.79\"/><path d=\"M4 3h.01\"/><path d=\"M22 8h.01\"/><path d=\"M15 2h.01\"/><path d=\"M22 20h.01\"/><path d=\"m22 2-2.24.75a2.9 2.9 0 0 0-1.96 3.12c.1.86-.57 1.63-1.45 1.63h-.38c-.86 0-1.6.6-1.76 1.44L14 10\"/><path d=\"m22 13-.82-.33c-.86-.34-1.82.2-1.98 1.11c-.11.7-.72 1.22-1.43 1.22H17\"/><path d=\"m11 2 .33.82c.34.86-.2 1.82-1.11 1.98C9.52 4.9 9 5.52 9 6.23V7\"/><path d=\"M11 13c1.93 1.93 2.83 4.17 2 5-.83.83-3.07-.07-5-2-1.93-1.93-2.83-4.17-2-5 .83-.83 3.07.07 5 2Z\"/>",
    "aliases": [
      "nightlife",
      "festival",
      "event",
      "fair",
      "circus",
      "festa",
      "evento"
    ]
  },
  {
    "id": "baby",
    "label": "Crianças",
    "svg": "<path d=\"M10 16c.5.3 1.2.5 2 .5s1.5-.2 2-.5\"/><path d=\"M15 12h.01\"/><path d=\"M19.38 6.813A9 9 0 0 1 20.8 10.2a2 2 0 0 1 0 3.6 9 9 0 0 1-17.6 0 2 2 0 0 1 0-3.6A9 9 0 0 1 12 3c2 0 3.5 1.1 3.5 2.5s-.9 2.5-2 2.5c-.8 0-1.5-.4-1.5-1\"/><path d=\"M9 12h.01\"/>",
    "aliases": [
      "playground",
      "kids",
      "family",
      "children-museum",
      "criancas",
      "infantil"
    ]
  },
  {
    "id": "paw-print",
    "label": "Animais",
    "svg": "<circle cx=\"11\" cy=\"4\" r=\"2\"/><circle cx=\"18\" cy=\"8\" r=\"2\"/><circle cx=\"20\" cy=\"16\" r=\"2\"/><path d=\"M9 10a5 5 0 0 1 5 5v3.5a3.5 3.5 0 0 1-6.84 1.045Q6.52 17.48 4.46 16.84A3.5 3.5 0 0 1 5.5 10Z\"/>",
    "aliases": [
      "animals",
      "farm-animals",
      "wildlife",
      "pet-friendly",
      "pet-service",
      "animal-experience",
      "horse-riding",
      "horse-carriage",
      "animais"
    ]
  },
  {
    "id": "camera",
    "label": "Fotografia",
    "svg": "<path d=\"M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z\"/><circle cx=\"12\" cy=\"13\" r=\"3\"/>",
    "aliases": [
      "camera",
      "photo-spot",
      "instagram-spot",
      "fotografia"
    ]
  },
  {
    "id": "sun",
    "label": "Pôr do sol",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"4\"/><path d=\"M12 2v2\"/><path d=\"M12 20v2\"/><path d=\"m4.93 4.93 1.41 1.41\"/><path d=\"m17.66 17.66 1.41 1.41\"/><path d=\"M2 12h2\"/><path d=\"M20 12h2\"/><path d=\"m6.34 17.66-1.41 1.41\"/><path d=\"m19.07 4.93-1.41 1.41\"/>",
    "aliases": [
      "sunset",
      "sunrise",
      "por-do-sol"
    ]
  },
  {
    "id": "compass",
    "label": "Experiências e guias",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z\"/>",
    "aliases": [
      "tour",
      "guided-tour",
      "experience",
      "class",
      "demonstration",
      "factory-tour",
      "guide",
      "tour-operator",
      "experiencia",
      "passeio"
    ]
  },
  {
    "id": "info",
    "label": "Informação turística",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"M12 16v-4\"/><path d=\"M12 8h.01\"/>",
    "aliases": [
      "tourism-info",
      "visitor-center",
      "informacoes"
    ]
  },
  {
    "id": "tickets",
    "label": "Ingressos",
    "svg": "<path d=\"m3.173 8.18 11-5a2 2 0 0 1 2.647.993L18.56 8\"/><path d=\"M6 10V8\"/><path d=\"M6 14v1\"/><path d=\"M6 19v2\"/><rect x=\"2\" y=\"8\" width=\"20\" height=\"13\" rx=\"2\"/>",
    "aliases": [
      "agency",
      "tickets",
      "reservation",
      "travel-agency",
      "ingressos",
      "agencia"
    ]
  },
  {
    "id": "volleyball",
    "label": "Esportes",
    "svg": "<path d=\"M11 7a16 16 20 0 1 10.98 4.362\"/><path d=\"M12 12a13 13 0 0 1-8.66 5\"/><path d=\"M16.83 13.634a16 16 0 0 1-9.267 7.328\"/><path d=\"M20.66 17A13 13 0 0 0 12 12a13 13 0 0 1 0-10\"/><path d=\"M8.17 15.366a16 16 0 0 1-1.713-11.69\"/><circle cx=\"12\" cy=\"12\" r=\"10\"/>",
    "aliases": [
      "football",
      "tennis",
      "golf",
      "sports-center",
      "stadium",
      "futebol",
      "esporte"
    ]
  },
  {
    "id": "waves-ladder",
    "label": "Natação",
    "svg": "<path d=\"M19 5a2 2 0 0 0-2 2v11\"/><path d=\"M2 18c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1\"/><path d=\"M7 13h10\"/><path d=\"M7 9h10\"/><path d=\"M9 5a2 2 0 0 0-2 2v11\"/>",
    "aliases": [
      "swimming",
      "natacao",
      "piscina"
    ]
  },
  {
    "id": "dumbbell",
    "label": "Academia",
    "svg": "<path d=\"M17.596 12.768a2 2 0 1 0 2.829-2.829l-1.768-1.767a2 2 0 0 0 2.828-2.829l-2.828-2.828a2 2 0 0 0-2.829 2.828l-1.767-1.768a2 2 0 1 0-2.829 2.829z\"/><path d=\"m2.5 21.5 1.4-1.4\"/><path d=\"m20.1 3.9 1.4-1.4\"/><path d=\"M5.343 21.485a2 2 0 1 0 2.829-2.828l1.767 1.768a2 2 0 1 0 2.829-2.829l-6.364-6.364a2 2 0 1 0-2.829 2.829l1.768 1.767a2 2 0 0 0-2.828 2.829z\"/><path d=\"m9.6 14.4 4.8-4.8\"/>",
    "aliases": [
      "gym",
      "running",
      "academia"
    ]
  },
  {
    "id": "square-parking",
    "label": "Estacionamento",
    "svg": "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\"/><path d=\"M9 17V7h4a3 3 0 0 1 0 6H9\"/>",
    "aliases": [
      "parking",
      "estacionamento"
    ]
  },
  {
    "id": "accessibility",
    "label": "Acessibilidade",
    "svg": "<circle cx=\"16\" cy=\"4\" r=\"1\"/><path d=\"m18 19 1-7-6 1\"/><path d=\"m5 8 3-3 5.5 3-2.36 3.5\"/><path d=\"M4.24 14.5a5 5 0 0 0 6.88 6\"/><path d=\"M13.76 17.5a5 5 0 0 0-6.88-6\"/>",
    "aliases": [
      "accessible",
      "wheelchair",
      "acessibilidade"
    ]
  },
  {
    "id": "plug-zap",
    "label": "Recarga elétrica",
    "svg": "<path d=\"M6.3 20.3a2.4 2.4 0 0 0 3.4 0L12 18l-6-6-2.3 2.3a2.4 2.4 0 0 0 0 3.4Z\"/><path d=\"m2 22 3-3\"/><path d=\"M7.5 13.5 10 11\"/><path d=\"M10.5 16.5 13 14\"/><path d=\"m18 3-4 4h6l-4 4\"/>",
    "aliases": [
      "electric-charging",
      "recarga"
    ]
  },
  {
    "id": "map-pin",
    "label": "Destino",
    "svg": "<path d=\"M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0\"/><circle cx=\"12\" cy=\"10\" r=\"3\"/>",
    "aliases": [
      "tourism",
      "destination",
      "location",
      "turismo",
      "destino"
    ]
  },
  {
    "id": "waterfall",
    "label": "Cachoeira",
    "aliases": [
      "waterfall",
      "cachoeira",
      "queda-dagua",
      "queda-d-agua"
    ],
    "svg": "<path d=\"M3 3h5v10l-3 3M21 3h-5v10l3 3M8 5h8M10 7v9M14 7v9M12 5v13M3 21c2-3 4-3 6 0 2-3 4-3 6 0 2-3 4-3 6 0\"/>"
  }
];
