import type {GeneratedStamp} from './types';import {escapeXML as esc,formatDate,formatVisit,formatLocation,fitText} from './formatters';import {createSeededRandom,hash} from './random';import {fontData} from './font';
export interface RenderOptions {idPrefix?:string;embedFont?:boolean;size?:number}
export function renderStampSVG(s:GeneratedStamp,renderOptions:RenderOptions={}){
 if(s.rendererVersion!==1)throw new Error('Renderer indisponível');
 const prefix=(renderOptions.idPrefix??`stamp-${hash(JSON.stringify(s))}`).replace(/[^a-zA-Z0-9_-]/g,'');
 const id=(name:string)=>`${prefix}-${name}`;const rnd=createSeededRandom(s.texture.seed);let holes='';
 for(let i=0;i<750;i++){const x=rnd.float()*320,y=rnd.float()*320,r=(.25+rnd.float()*1.2)*s.texture.level;holes+=`<ellipse cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" rx="${r.toFixed(2)}" ry="${(r*.6).toFixed(2)}" fill="black"/>`;}
 const name=s.data.partnerName.toLocaleUpperCase('pt-BR'),date=formatDate(s.data.visitDate),visit=formatVisit(s.data.visitNumber),location=formatLocation(s.data.city,s.data.state);
 const status={first_visit:'',visited:'',return:'RETORNO',favorite:'FAVORITO',special:'EDIÇÃO ESPECIAL',completed_route:'ROTEIRO COMPLETO',seasonal:'EVENTO'}[s.data.status??'visited'];
 const detail=s.options.detail??'full';const a11y=s.options.ariaLabel??`Carimbo de ${s.data.partnerName}. ${date}. ${visit}. ${location}. ${status}`;
 const text=(value:string,x:number,y:number,maxWidth:number,size=20)=>{if(!value)return '';const count=Array.from(value).length;const width=Math.min(maxWidth,count*size*.48);return `<text x="${x}" y="${y}" text-anchor="middle" font-size="${size}" letter-spacing="1.1"${width?` textLength="${width.toFixed(2)}" lengthAdjust="spacingAndGlyphs"`:''}>${esc(value)}</text>`;};
 const title=(y:number,width=204)=>{const f=fitText(name,width);return f.lines.map((l,i)=>text(l,160,y+i*(f.size+3),width,f.size)).join('');};
 const icon=(x:number,y:number,size:number)=>`<g mask="url(#${id('ink')})" ${s.texture.level?`filter="url(#${id('grain')})"`:''}><g data-stamp-icon="${esc(s.icon.id)}" transform="translate(${x} ${y}) scale(${size/24})" fill="none" stroke="currentColor" stroke-width="1.85" stroke-linecap="round" stroke-linejoin="round">${s.icon.svg}</g></g>`;
 const full=detail==='full';const normal=detail!=='compact';
 const foot=(y=228,width=196)=>`${normal?text(date,160,y,width,24):''}${full&&s.options.showVisitNumber!==false?text([visit,status].filter(Boolean).join(' • '),160,y+24,width,15):''}${full&&s.options.showLocation!==false?text(location,160,y+44,width,13):''}`;
 let body='';
 if(detail==='compact')body=icon(112,90,96)+title(224,190);
 else if(s.layout==='radial'||s.layout==='seal'){
  const titleLength=Math.min(325,name.length*14);body=`<text font-size="${name.length>32?23:30}" letter-spacing="1.3" text-anchor="middle" textLength="${titleLength}" lengthAdjust="spacingAndGlyphs"><textPath href="#${id('arc')}" startOffset="50%">${esc(name)}</textPath></text>`+icon(s.layout==='seal'?103:112,106,s.layout==='seal'?114:96)+foot(232,188);
 }else if(s.layout==='split'){
  body=title(92,210)+icon(61,125,78)+`<path d="M155 132V203" stroke="currentColor" stroke-width="1"/>`+text(date,219,151,115,21)+(full&&s.options.showVisitNumber!==false?text(visit,219,175,112,15):'')+(full?text(status,219,196,112,12):'')+(full&&s.options.showLocation!==false?text(location,160,239,194,15):'');
 }else if(s.layout==='iconTop')body=icon(124,62,72)+title(164,204)+foot(232,190);
 else if(s.layout==='banner')body=icon(124,60,72)+`<path d="M58 144H262M58 200H262" stroke="currentColor" stroke-width="1.6"/>`+title(name.length>28?164:183,195)+foot(231,185);
 else if(s.layout==='ruled')body=title(85,203)+`<path d="M90 119H230" stroke="currentColor" stroke-width="1.4"/>`+icon(122,125,76)+foot(230,187);
 else body=title(88,204)+icon(119,122,82)+foot(232,184);
 const transform=s.shape.contentTransform??{x:s.shape.safeArea.x-50*s.shape.safeArea.width/220,y:s.shape.safeArea.y-58*s.shape.safeArea.height/230,scaleX:s.shape.safeArea.width/220,scaleY:s.shape.safeArea.height/230};
 const contentTransform=`translate(${transform.x} ${transform.y}) scale(${transform.scaleX} ${transform.scaleY})`;
 const border=`<path d="${s.shape.path}" fill="none" stroke="currentColor" stroke-width="4"/><path d="${s.shape.path}" transform="translate(9.6 9.6) scale(.94)" fill="none" stroke="currentColor" stroke-width="1.5"/>${['double-circle','double-border'].includes(s.shape.id)?`<path d="${s.shape.path}" transform="translate(18 18) scale(.8875)" fill="none" stroke="currentColor" stroke-width="1"/>`:''}`;
 const size=renderOptions.size??(typeof s.options.size==='number'?s.options.size:({sm:96,md:240,lg:512}[s.options.size??'md']));
 return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 320 320" role="img" aria-labelledby="${id('title')} ${id('desc')}" data-shape="${s.shape.id}" data-layout="${s.layout}" style="color:${s.color};max-width:100%;height:auto"><title id="${id('title')}">${esc(a11y)}</title><desc id="${id('desc')}">Um único ícone de ${esc(s.icon.label)}. Carimbo vetorial de visita.</desc><defs>${renderOptions.embedFont?`<style>@font-face{font-family:'Stamp Condensed';src:url('${fontData}') format('woff');font-weight:700;}</style>`:''}<path id="${id('arc')}" d="M48 160 A112 112 0 0 1 272 160"/><mask id="${id('ink')}" maskUnits="userSpaceOnUse" x="-100" y="-100" width="520" height="520"><rect x="-100" y="-100" width="520" height="520" fill="white"/>${holes}</mask><filter id="${id('grain')}" x="-5%" y="-5%" width="110%" height="110%"><feTurbulence type="fractalNoise" baseFrequency=".7" numOctaves="3" seed="${s.texture.seed}" result="grain"/><feColorMatrix in="grain" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 12 ${(-3.1-s.texture.level*2).toFixed(2)}" result="grainMask"/><feComposite in="SourceGraphic" in2="grainMask" operator="in"/></filter><filter id="${id('rough')}" x="-10%" y="-10%" width="120%" height="120%"><feTurbulence type="fractalNoise" baseFrequency=".075" numOctaves="2" seed="${s.texture.seed}" result="noise"/><feDisplacementMap in="SourceGraphic" in2="noise" scale="${(s.texture.level*3.5).toFixed(2)}" xChannelSelector="R" yChannelSelector="G"/></filter></defs><g transform="rotate(${s.rotation} 160 160)" fill="currentColor" font-family="'Stamp Condensed','Arial Narrow',sans-serif" font-weight="700"><g mask="url(#${id('ink')})" ${s.texture.level?`filter="url(#${id('rough')})"`:''}>${border}</g><g transform="${contentTransform}" mask="url(#${id('ink')})">${body}</g></g></svg>`;
}
export const renderToString=renderStampSVG;
