import {z} from 'zod';import fixture from '../../../seed/validation-trip.json';import type {TripData,TripItem} from './types';import type {ContentData} from '@/core/db/schema';
export const profileSchema=z.object({startsOn:z.string().regex(/^2026-09-(12|13|14)$/),endsOn:z.string().regex(/^2026-09-(12|13|14)$/),party:z.enum(['couple','family','friends','solo']),interests:z.array(z.string()).min(1),intentions:z.array(z.string()).min(1),pace:z.enum(['slow','balanced','active']),transport:z.enum(['car','walk','taxi','unknown']),needs:z.array(z.string()).default([])}).refine(p=>p.endsOn>=p.startsOn,{message:'A saída deve ser igual ou posterior à chegada.'});
export type Profile=z.infer<typeof profileSchema>;
export interface TravelEngine {generate(profile:Profile,places:ContentData[],existing:TripData):TripData;}
export const demoTravelEngine:TravelEngine={generate(input,places,existing){const profile=profileSchema.parse(input);const result=structuredClone(existing);const dates=fixture.days.map(d=>d.date).filter(d=>d>=profile.startsOn&&d<=profile.endsOn);const protectedItems=existing.days.flatMap(d=>d.items.filter(i=>i.state==='fixed'||i.source!=='recommended_by_engine').map(i=>({date:d.date,item:i})));if(protectedItems.some(p=>!dates.includes(p.date)))throw new Error('Há escolhas manuais fora do novo período. Mantenha as datas ou ajuste essas paradas antes de gerar.');
const eligible=places.filter(p=>p.categoryIds?.some(c=>profile.interests.includes(c))&&(!profile.needs.includes('avoid_outdoor')||p.environment!=='outdoor')&&(!profile.needs.includes('free')||p.costType==='free'));
const used=new Set(protectedItems.map(p=>p.item.placeId));result.days=dates.map(date=>{const manual=protectedItems.filter(p=>p.date===date).map(p=>structuredClone(p.item));const target=profile.pace==='slow'?2:profile.pace==='active'?4:3;const candidates=[...(fixture.days.find(d=>d.date===date)?.items||[]).map(i=>places.find(p=>p.id===i.placeId)).filter((p):p is ContentData=>!!p),...eligible].filter(p=>eligible.some(e=>e.id===p.id));const items:TripItem[]=[...manual];for(const p of candidates){if(items.filter(i=>i.state!=='removed').length>=target)break;if(used.has(p.id))continue;used.add(p.id);const original=fixture.days.find(d=>d.date===date)?.items.find(i=>i.placeId===p.id);items.push(original?{...original,state:'planned'}:{id:`generated-${date}-${p.id}`,placeId:p.id,startsAt:items.length===0?'09:00':items.length===1?'12:00':items.length===2?'15:00':'17:00',durationMinutes:p.durationMinutes||60,source:'recommended_by_engine',state:'planned'});}return{date,items:items.sort((a,b)=>a.startsAt.localeCompare(b.startsAt))};});result.trip={...result.trip,...profile};return result;}};
export type TripOperation={action:'move'|'remove'|'swap'|'add'|'fix'|'unfix'|'restore';itemId?:string;placeId?:string;date?:string;time?:string;newId?:string};
export function applyOperation(existing:TripData,op:TripOperation,places:ContentData[]):TripData{const result=structuredClone(existing);const day=result.days.find(d=>d.items.some(i=>i.id===op.itemId));const item=day?.items.find(i=>i.id===op.itemId);const destination=result.days.find(d=>d.date===op.date);const place=places.find(p=>p.id===op.placeId);if(op.action==='add'){if(!destination||!place||!op.newId)throw new Error('Selecione dia e lugar disponíveis.');if(destination.items.some(i=>i.placeId===place.id&&i.state!=='removed'))throw new Error('Este lugar já está planejado neste dia.');destination.items.push({id:op.newId,placeId:place.id,startsAt:op.time||'17:00',durationMinutes:place.durationMinutes||60,source:'added_by_user',state:'planned'});}else{if(!day||!item)throw new Error('Parada indisponível.');if(item.state==='fixed'&&op.action!=='unfix')throw new Error('Desfixe esta parada antes de alterar.');if(op.action==='fix')item.state='fixed';if(op.action==='unfix')item.state='planned';if(op.action==='remove'){item.previousState=item.state;item.state='removed';}if(op.action==='restore'){item.state=item.previousState||'planned';delete item.previousState;}if(op.action==='swap'){if(!place)throw new Error('Selecione um lugar disponível.');item.placeId=place.id;item.durationMinutes=place.durationMinutes||60;item.state='planned';}if(op.action==='move'){if(!destination||!op.time)throw new Error('Selecione dia e horário.');day.items=day.items.filter(i=>i.id!==item.id);destination.items.push(item);item.startsAt=op.time;item.state='moved';}item.source='changed_by_user';}
for(const d of result.days)for(const i of d.items)if(i.state!=='removed'&&minutes(i.startsAt)+i.durationMinutes>1440)throw new Error('A parada ultrapassa o fim do dia. Escolha outro horário.');
for(const d of result.days)d.items.sort((a,b)=>a.startsAt.localeCompare(b.startsAt));return result;}
export function minutes(time:string){const[h,m]=time.split(':').map(Number);return h*60+m;}
export function timeLabel(value:number){return `${Math.floor(value/60).toString().padStart(2,'0')}:${(value%60).toString().padStart(2,'0')}`;}
