'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState,useSyncExternalStore,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import type {ContentData} from '@/core/db/schema';
import {MockMap} from '@/components/content';
import {Book,type BookPage} from '@/modules/passport/Book';
import {passportSummary} from '@/modules/passport/model';
import {applyOperation,type TripOperation} from './engine';
import type {TripItem} from './types';
import {addGuestVisit,clearGuestDraft,markGuestSavePending,readGuestDraft,subscribeGuestDraft,withUpdatedGuestData,writeGuestDraft,type GuestTripDraft} from './guest-trip';
import {saveGuestTrip} from './guest-actions';

type ExperienceProps={places:ContentData[];categories?:ContentData[];initialDay?:string};

function useGuestDraft(){const draft=useSyncExternalStore(subscribeGuestDraft,readGuestDraft,()=>null);const commit=useCallback((next:GuestTripDraft)=>writeGuestDraft(next),[]);return{draft,commit};}

function EmptyGuestState(){return <section className="route-state panel"><p className="eyebrow">Experiência de apresentação</p><h1>Monte seu roteiro para começar.</h1><p>Você pode conhecer todo o fluxo sem criar conta. O login só será solicitado quando decidir salvar a viagem.</p><Link className="button primary" href="/roteiro">Montar meu roteiro</Link></section>;}

function SaveTripButton({draft,label='Salvar minha viagem'}:{draft:GuestTripDraft;label?:string}){
  const router=useRouter();const[pending,start]=useTransition();const[message,setMessage]=useState('');
  return <><button className="primary" disabled={pending} onClick={()=>start(async()=>{setMessage('');const result=await saveGuestTrip(draft);if(result.ok&&result.tripId){clearGuestDraft();router.push(`/viagens/${result.tripId}/roteiro`);return;}if(result.requiresAuth){markGuestSavePending();router.push('/login?next=%2Fexperiencia%2Fsalvar');return;}setMessage(result.message);})}>{pending?'Salvando…':label}</button>{message&&<p role="alert">{message}</p>}</>;
}

function ExperienceHeader({draft,active}:{draft:GuestTripDraft;active:'roteiro'|'calendario'|'passaporte'|'compartilhar'}){return <><div className="guest-experience-banner" role="note"><strong>Modo apresentação</strong><span>Explore tudo agora. Entre apenas quando quiser salvar ou validar registros reais.</span></div><nav className="chips guest-experience-nav" aria-label="Experiência da viagem"><Link className="button" aria-current={active==='roteiro'?'page':undefined} href="/experiencia/roteiro">Roteiro</Link><Link className="button" aria-current={active==='calendario'?'page':undefined} href="/experiencia/calendario">Calendário</Link><Link className="button" aria-current={active==='passaporte'?'page':undefined} href="/experiencia/passaporte">Passaporte</Link><Link className="button" aria-current={active==='compartilhar'?'page':undefined} href="/experiencia/compartilhar">Compartilhar</Link><SaveTripButton draft={draft}/></nav></>;}

function GuestItemEditor({draft,item,places,commit}:{draft:GuestTripDraft;item?:TripItem;places:ContentData[];commit:(next:GuestTripDraft)=>void}){
  const[message,setMessage]=useState('');const fixed=item?.state==='fixed';
  function run(operation:TripOperation['action'],form:HTMLFormElement){try{const data=new FormData(form);const op:TripOperation={action:operation,itemId:item?.id,placeId:String(data.get('placeId')||''),date:String(data.get('date')||''),time:String(data.get('time')||'17:00'),newId:crypto.randomUUID()};const next=applyOperation(draft.data,op,places);commit(withUpdatedGuestData(draft,next));setMessage('Alteração aplicada nesta demonstração.');}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível alterar a parada.');}}
  const currentDay=draft.data.days.find(day=>day.items.some(i=>i.id===item?.id));
  return <details><summary>{item?'Editar parada':'Adicionar parada'}</summary><form onSubmit={e=>e.preventDefault()}><label className="field">Dia<select aria-label="Dia da parada" name="date" defaultValue={currentDay?.date||draft.data.days[0]?.date}>{draft.data.days.map(day=><option key={day.date} value={day.date}>{day.date}</option>)}</select></label>{!fixed&&item?.state!=='removed'&&<><label className="field">Horário<input aria-label="Horário da parada" name="time" type="time" defaultValue={item?.startsAt||'17:00'} required/></label><label className="field">Lugar<select aria-label="Lugar da parada" name="placeId" defaultValue={item?.placeId||places[0]?.id}>{places.filter(p=>p.discoveryVisible!==false&&p.status!=='archived').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></>}<div className="actions">{!item?<button type="button" onClick={e=>run('add',e.currentTarget.form!)}>Adicionar</button>:fixed?<button type="button" onClick={e=>run('unfix',e.currentTarget.form!)}>Desfixar</button>:item.state==='removed'?<button type="button" onClick={e=>run('restore',e.currentTarget.form!)}>Restaurar parada</button>:<><button type="button" onClick={e=>run('move',e.currentTarget.form!)}>Mover</button><button type="button" onClick={e=>run('swap',e.currentTarget.form!)}>Trocar</button><button type="button" onClick={e=>run('fix',e.currentTarget.form!)}>Fixar</button><button type="button" onClick={e=>run('remove',e.currentTarget.form!)}>Remover</button></>}</div>{message&&<p role="status">{message}</p>}</form></details>;
}

function placeName(places:ContentData[],id:string){return places.find(place=>place.id===id)?.name||'Lugar indisponível';}

export function GuestRouteExperience({places,initialDay}:ExperienceProps){const{draft,commit}=useGuestDraft();if(!draft)return <EmptyGuestState/>;const day=draft.data.days.find(d=>d.date===initialDay)||draft.data.days[0];if(!day)return <EmptyGuestState/>;const active=day.items.filter(item=>item.state!=='removed');return <><ExperienceHeader draft={draft} active="roteiro"/><p className="eyebrow">Sua viagem em Serra Negra</p><h1 className="compact">Seu roteiro, dia a dia.</h1><p>{draft.data.trip.startsOn} a {draft.data.trip.endsOn} · experiência temporária salva neste navegador</p><nav className="chips section" aria-label="Dias da viagem">{draft.data.days.map((d,index)=><Link className="button" aria-current={d.date===day.date?'page':undefined} key={d.date} href={`/experiencia/roteiro?day=${d.date}`}>Dia {index+1} · {d.date}</Link>)}</nav><div className="two"><div><h2>Paradas de {day.date}</h2><div className="timeline">{active.map(item=>{const place=places.find(p=>p.id===item.placeId);const simulated=draft.data.visits.some(v=>v.placeId===item.placeId&&v.occurredAt.slice(0,10)===day.date);return <article className="card" key={item.id}><span className="eyebrow">{item.startsAt}</span><h3>{place?.name||'Lugar indisponível'}</h3><p>{place?.shortDescription}</p><div className="actions"><span className="badge">{item.state==='fixed'?'Fixado':'Planejado'}</span><button type="button" aria-pressed={simulated} onClick={()=>commit(addGuestVisit(draft,item.placeId,day.date))}>{simulated?'Remover carimbo simulado':'Simular carimbo'}</button></div><small>Carimbos desta etapa são apenas demonstrativos e não valem como evidência de presença.</small><GuestItemEditor draft={draft} item={item} places={places} commit={commit}/></article>;})}</div>{!active.length&&<p className="empty">Dia livre. Adicione uma parada.</p>}<section className="panel"><h2>Adicionar uma parada</h2><GuestItemEditor draft={draft} places={places} commit={commit}/></section>{day.items.some(i=>i.state==='removed')&&<section className="section"><h2>Paradas removidas</h2>{day.items.filter(i=>i.state==='removed').map(item=><article className="panel" key={item.id}><h3>{placeName(places,item.placeId)}</h3><GuestItemEditor draft={draft} item={item} places={places} commit={commit}/></article>)}</section>}</div><aside className="stack" style={{alignContent:'start'}}><MockMap places={active.flatMap(item=>{const place=places.find(p=>p.id===item.placeId);return place?[place]:[]})}/><section className="panel"><h2>Seu planejamento</h2><p>{active.length} paradas · {active.reduce((sum,item)=>sum+item.durationMinutes,0)} min em atividades.</p><p>Edite livremente. Nada exige conta até você escolher salvar.</p></section></aside></div></>;}

export function GuestCalendarExperience({places}:ExperienceProps){const{draft}=useGuestDraft();if(!draft)return <EmptyGuestState/>;return <><ExperienceHeader draft={draft} active="calendario"/><p className="eyebrow">Visão geral</p><h1>Calendário da viagem</h1><p>Veja a distribuição antes de salvar. Alterações continuam disponíveis no roteiro.</p><div className="calendar-week">{draft.data.days.map((day,index)=><article className="card" key={day.date}><span className="eyebrow">Dia {index+1}</span><h2>{day.date}</h2><ul>{day.items.filter(item=>item.state!=='removed').map(item=><li key={item.id}>{item.startsAt} · {placeName(places,item.placeId)}{draft.data.visits.some(v=>v.placeId===item.placeId&&v.occurredAt.slice(0,10)===day.date)?' · carimbo simulado':''}</li>)}</ul><Link className="button" href={`/experiencia/roteiro?day=${day.date}`}>Abrir este dia</Link></article>)}</div></>}

function GuestStamp({name,date,number}:{name:string;date:string;number:number}){return <div className="stamp guest-demo-stamp"><p className="eyebrow">Carimbo de demonstração</p><strong>{name}</strong><small>{new Date(`${date}T12:00:00Z`).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'})} · VISITA Nº {number}</small><p>Prévia visual. Uma presença real só é registrada após validação na experiência autenticada.</p></div>;}

export function GuestPassportExperience({places,categories=[]}:ExperienceProps){const{draft}=useGuestDraft();if(!draft)return <EmptyGuestState/>;const summary=passportSummary(draft.data,places);const plannedIds=[...new Set(summary.planned.map(item=>item.placeId))];const pages:BookPage[]=[{id:'cover',title:'Minha história em Serra Negra',content:<div className="passport-cover"><p className="eyebrow">PASSAPORTE SERRA NEGRA · DEMONSTRAÇÃO</p><h3>Descubra. Planeje. Experimente.</h3><p>Veja como a memória da viagem se forma antes mesmo de criar sua conta.</p><small>Não é documento oficial.</small></div>},{id:'identity',title:'Identificação da viagem',content:<dl><dt>Modo</dt><dd>Apresentação temporária</dd><dt>Destino</dt><dd>Serra Negra, SP</dd><dt>Período</dt><dd>{draft.data.trip.startsOn} a {draft.data.trip.endsOn}</dd><dt>Paradas planejadas</dt><dd>{summary.planned.length}</dd></dl>},{id:'planned',title:'Próximas marcas',content:<><p>Estes lugares já fazem parte do seu roteiro:</p><ul>{plannedIds.map(id=><li key={id}>{placeName(places,id)}</li>)}</ul><Link href="/experiencia/roteiro">Voltar ao roteiro e simular carimbos</Link></>},...(summary.visits.length?Array.from({length:Math.ceil(summary.visits.length/3)},(_,group):BookPage=>({id:`stamps-${group}`,title:'Marcas simuladas',content:summary.visits.slice(group*3,group*3+3).map(v=><GuestStamp key={v.id} name={placeName(places,v.placeId)} date={v.occurredAt.slice(0,10)} number={v.visitNumber}/>) })):[]),{id:'interests',title:'Interesses pelo caminho',content:<><p>Categorias relacionadas às marcas simuladas:</p><ul>{categories.filter(c=>summary.categories.includes(c.id)).map(c=><li key={c.id}>{c.name}</li>)}</ul>{!summary.categories.length&&<p>Simule um carimbo no roteiro para visualizar esta parte.</p>}</>},{id:'journey',title:'Caminho da viagem',content:<><MockMap places={(summary.recordedIds.length?summary.recordedIds:plannedIds).flatMap(id=>{const p=places.find(place=>place.id===id);return p?[p]:[]})}/><p>{summary.recordedIds.length?'Mapa das marcas simuladas.':'Enquanto não há carimbos, mostramos as paradas planejadas.'}</p></>},{id:'summary',title:'Sua viagem pode continuar',content:<><p>{summary.planned.length} paradas planejadas · {summary.visits.length} carimbos simulados.</p><p>Ao salvar, o roteiro e suas edições são persistidos. Carimbos simulados não viram evidência real.</p><div className="actions"><SaveTripButton draft={draft} label="Salvar esta viagem"/><Link className="button" href="/experiencia/compartilhar">Ver compartilhamento</Link></div></>}];return <><ExperienceHeader draft={draft} active="passaporte"/><p className="eyebrow">Passaporte aberto sem login</p><h1 className="compact">Meu Passaporte</h1><p>Esta é a experiência completa de apresentação. Você pode navegar pelo Passaporte agora; autenticação só entra quando houver algo real para salvar ou validar.</p><Book pages={pages}/></>}

export function GuestShareExperience({places}:ExperienceProps){const{draft}=useGuestDraft();const[copied,setCopied]=useState(false);if(!draft)return <EmptyGuestState/>;const planned=draft.data.days.flatMap(day=>day.items.filter(item=>item.state!=='removed'));const summary=`Minha viagem para Serra Negra: ${draft.data.trip.startsOn} a ${draft.data.trip.endsOn}, ${planned.length} paradas planejadas. Passaporte Serra Negra.`;async function share(){if(typeof navigator!=='undefined'&&navigator.share){await navigator.share({title:'Minha viagem em Serra Negra',text:summary});return;}await navigator.clipboard.writeText(summary);setCopied(true);}return <><ExperienceHeader draft={draft} active="compartilhar"/><p className="eyebrow">Prévia de compartilhamento</p><h1>Compartilhe a ideia da viagem</h1><section className="panel"><p>{summary}</p><ul>{planned.slice(0,8).map(item=><li key={item.id}>{placeName(places,item.placeId)}</li>)}</ul><div className="actions"><button className="primary" onClick={()=>void share()}>{copied?'Resumo copiado':'Compartilhar resumo'}</button><SaveTripButton draft={draft} label="Salvar e gerar experiência persistente"/></div><p className="muted">O link público permanente é gerado depois que a viagem é salva. Até lá, nenhum dado é publicado.</p></section></>}

export function GuestSaveExperience(){const{draft}=useGuestDraft();const router=useRouter();const started=useRef(false);const[message,setMessage]=useState('Preparando sua viagem…');useEffect(()=>{if(!draft||started.current)return;started.current=true;void saveGuestTrip(draft).then(result=>{if(result.ok&&result.tripId){clearGuestDraft();router.replace(`/viagens/${result.tripId}/roteiro`);return;}if(result.requiresAuth){markGuestSavePending();router.replace('/login?next=%2Fexperiencia%2Fsalvar');return;}started.current=false;setMessage(result.message);});},[draft,router]);const displayMessage=draft?message:'Não encontramos uma viagem temporária para salvar.';return <section className="route-state panel" role="status" aria-live="polite"><p className="eyebrow">Salvando sua experiência</p><h1>Seu roteiro continua com você.</h1><p>{displayMessage}</p>{!draft&&<Link className="button primary" href="/roteiro">Montar um roteiro</Link>}</section>}
