import Link from 'next/link';
import {Icon} from '@/design-system/icons';
import type {ContentData} from '@/core/db/schema';
import {mapsProvider,weatherProvider} from '@/providers';
import {placeUrl} from '@/modules/content/repository';
export const labels:Record<string,string>={tourist_point:'Ponto turístico fictício',business:'Estabelecimento fictício',partner:'Parceiro fictício',public_point:'Ponto público fictício',free:'Sem custo',paid:'Pago',paid_with_booking:'Pago com reserva',free_with_booking:'Gratuito com reserva',mixed:'Misto',unknown:'Não informado',indoor:'Ambiente interno',outdoor:'Ao ar livre',within_1_hour:'Em até 1 hora',same_day:'No mesmo dia',within_few_hours:'Em algumas horas',partly_cloudy:'Parcialmente nublado',rain:'Chuva',clear:'Céu aberto',planned:'Planejado',fixed:'Fixado',moved:'Movido',removed:'Removido'};
export function PlaceCard({place}:{place:ContentData}){return <article className="card" data-testid={`place-card-${place.id}`}><img className="placeholder" src="/placeholders/card.svg" alt={`Placeholder de imagem de ${place.name}`}/><span className="eyebrow">{labels[place.commercialRelation||'']||labels[place.placeType||'']}</span><h3><Link href={placeUrl(place)}>{place.name}</Link></h3><p>{place.shortDescription}</p><div className="actions"><small><Icon name="lugar-duracao-sugerida" size="xs"/> {place.durationMinutes} min</small><span className="badge">{labels[place.environment||'']}</span></div></article>;}
export function MockMap({places}:{places:ContentData[]}){const points=mapsProvider.points(places);return <div className="map" data-testid="mock-map"><p><Icon name="mapa"/> <strong>Mapa de demonstração</strong></p><small>Posições esquemáticas. Não serve para navegação real.</small><svg viewBox="0 0 110 110" role="img" aria-label={`${places.length} lugares no mapa esquemático`}><path d="M10 30H100M10 65H100M30 10V100M65 10V100" stroke="currentColor" opacity=".2" fill="none"/>{points.map((p,i)=><g key={p.id}><circle cx={p.x} cy={p.y} r="5" fill="var(--surface-raised)" stroke="currentColor"/><text x={p.x} y={p.y+1.5} textAnchor="middle" fontSize="5" fill="currentColor">{i+1}</text></g>)}</svg><ol>{places.map(p=><li key={p.id}><Link href={placeUrl(p)}>{p.name}</Link></li>)}</ol>{!places.length&&<p>Nenhum marcador nesta seleção.</p>}</div>;}
export function Weather({date='2026-09-12'}:{date?:string}){const w=weatherProvider.forDate(date);return <aside className="notice" aria-label="Clima demo"><Icon name={w?.condition==='rain'?'clima-chuva':'sol'}/> <strong>Clima simulado · {date}</strong><p>{w?`${labels[w.condition]} · ${w.temperatureC} °C · ${w.rainProbability}% de chance de chuva`:'Sem previsão demo para esta data.'}</p></aside>;}
export function EventList({events}:{events:ContentData[]}){return <section><h2>Eventos de demonstração</h2>{events.length?events.map(e=><article className="panel" key={e.id}><h3>{e.name}</h3><p>{e.startsAt?new Date(e.startsAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):''}</p><span className="badge">{labels[e.costType||'']}</span></article>):<p className="empty">Nenhum evento informado nesta seleção.</p>}</section>;}
