"use client";
import {useState} from "react";import {useRouter} from "next/navigation";import {Icon} from "@/design-system/icons";import {Button} from "./ui";
const steps=[
 {key:'when',title:'Quando?',choices:['12–14 SET 2026 (DEMO)']},
 {key:'party',title:'Com quem?',choices:['casal','família','amigos','sozinho']},
 {key:'interests',title:'O que interessa?',choices:['gastronomia','natureza','cultura','cafés']},
 {key:'intent',title:'O que quer viver?',choices:['conhecer os clássicos','comer bem','ver paisagens','relaxar']},
 {key:'pace',title:'Ritmo',choices:['tranquilo','equilibrado','ativo']},
 {key:'transport',title:'Transporte',choices:['carro','a pé','aplicativo/táxi','ainda não sei']},
 {key:'needs',title:'Necessidades importantes',choices:['nenhuma','acessibilidade','preferir opções gratuitas','evitar outdoor']},
] as const;
async function track(name:string,payload:Record<string,unknown>){try{await fetch('/api/tracking',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,payload})})}catch{}}
export function OnboardingClient(){const router=useRouter();const [step,setStep]=useState(0);const [answers,setAnswers]=useState<Record<string,string[]>>({when:['12–14 SET 2026 (DEMO)'],party:['casal'],interests:['gastronomia','natureza'],intent:['comer bem'],pace:['equilibrado'],transport:['carro'],needs:['nenhuma']});const current=steps[step];function toggle(key:string,value:string){setAnswers(a=>{const multi=key==='interests'||key==='intent';const prev=a[key]||[];const next=multi?(prev.includes(value)?prev.filter(v=>v!==value):[...prev,value]):[value];return {...a,[key]:next}})}async function finish(){await track('ROUTE_STARTED',{...answers,mode:'demo'});await track('TRIP_CREATED',{tripId:'demo-trip-001',mode:'existing-demo'});router.push('/viagens/demo-trip-001/roteiro')}if(step>=steps.length)return <div className="card card-body stack-lg"><div className="section-head"><span className="eyebrow">Revisão</span><h2>Seu perfil desta viagem</h2><p>O perfil pertence à viagem e não é tratado como característica permanente.</p></div><div className="stack">{Object.entries(answers).map(([k,v])=><div key={k}><strong>{k}</strong><div className="muted">{v.join(', ')}</div></div>)}</div><div className="cluster"><Button onClick={()=>setStep(steps.length-1)} variant="secondary"><Icon name="voltar" size="sm"/>Voltar</Button><Button onClick={finish}>Gerar roteiro demo<Icon name="avancar" size="sm"/></Button></div></div>;return <div className="card card-body stack-lg"><div className="stepper" aria-label={`Etapa ${step+1} de ${steps.length+1}`}>{Array.from({length:steps.length+1},(_,i)=><span key={i} className={`step-dot ${i<=step?'active':''}`}/>)}</div><div className="section-head"><span className="eyebrow">Etapa {step+1}</span><h2>{current.title}</h2></div><div className="choice-grid">{current.choices.map(choice=>{const active=(answers[current.key]||[]).includes(choice);return <button key={choice} className="choice" aria-pressed={active} onClick={()=>toggle(current.key,choice)}>{choice}</button>})}</div><div className="spread"><Button variant="secondary" disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))}><Icon name="voltar" size="sm"/>Voltar</Button><Button onClick={()=>setStep(s=>s+1)}>Continuar<Icon name="avancar" size="sm"/></Button></div></div>}
