from pathlib import Path
import json, shutil, html
R=Path(__file__).resolve().parents[1]; OUT=R/'static-preview'; OUT.mkdir(exist_ok=True)
(OUT/'assets').mkdir(exist_ok=True)
for f in (R/'public/placeholders').glob('*.svg'): shutil.copy2(f,OUT/'assets'/f.name)
css=(R/'src/app/globals.css').read_text(); (OUT/'styles.css').write_text(css+'\n.static-note{position:fixed;right:.7rem;bottom:.7rem;z-index:20;padding:.45rem .65rem;background:#111;color:#fff;border-radius:.4rem;font:12px system-ui}.static-nav{display:flex;gap:.6rem;flex-wrap:wrap;margin-top:.5rem}.static-nav a{font-weight:700}.media img{position:static!important}\n')
c=json.loads((R/'seed/validation-content.json').read_text()); t=json.loads((R/'seed/validation-trip.json').read_text()); places=c['places']; cats={x['id']:x for x in c['categories']}
def shell(title,body):
 nav=''.join(f'<a href="{f}">{n}</a>' for f,n in [('index.html','Home'),('explorar.html','Explorar'),('lugar.html','Lugar'),('parceiro.html','Parceiro'),('roteiro.html','Roteiro'),('calendario.html','Calendário'),('passaporte.html','Passaporte'),('admin.html','Admin')])
 return f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)}</title><link rel="stylesheet" href="styles.css"></head><body><div class="demo-banner">Modo de validação — conteúdo fictício</div><header class="site-header"><div class="container site-header-inner"><strong class="brand">Passaporte Serra Negra<small>STATIC VISUAL FALLBACK</small></strong><nav class="static-nav">{nav}</nav></div></header><main id="conteudo">{body}</main><footer class="site-footer"><div class="container"><strong>Validação visual offline</strong><p class="muted">Render estático derivado dos mesmos seeds e tokens. Não valida Next.js nem banco.</p></div></footer><div class="static-note">STATIC FALLBACK</div></body></html>'''
def card(p):
 cs=' '.join(cats[x]['name'] for x in p['categoryIds'] if x in cats)
 return f'<article class="card"><div class="media ratio-card"><img src="assets/card-4x3.svg" alt="placeholder"></div><div class="card-body"><span class="eyebrow">{"Parceiro" if p["commercialRelation"]=="partner" else "Ponto"} fictício</span><h3>{html.escape(p["name"])}</h3><p class="muted">{html.escape(p["shortDescription"])}</p><span class="badge">{html.escape(cs)}</span></div></article>'
home=f'''<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="badge warning">Conteúdo sintético</span><h1>Planeje a viagem. Viva a cidade. Guarde o caminho.</h1><p>Vertical slice para descoberta, roteiro e memória.</p><div class="cluster"><a class="button" href="roteiro.html">Montar roteiro</a><a class="button secondary" href="explorar.html">Explorar</a></div></div><div class="hero-media media ratio-hero"><img src="assets/hero-16x9.svg" alt="placeholder"></div></div></section><section class="section"><div class="container"><div class="section-head"><span class="eyebrow">Descoberta</span><h2>Lugares de validação</h2></div><div class="card-grid">{''.join(card(p) for p in places[:6])}</div></div></section>'''
(OUT/'index.html').write_text(shell('Home',home))
explore=f'''<div class="container section"><div class="section-head"><span class="eyebrow">Explorar</span><h1>O que cabe nesta viagem?</h1></div><div class="explore-layout"><div class="stack-lg"><div class="search-panel"><input class="input" placeholder="Buscar lugares"><div class="filters"><button class="filter-chip">Parceiros</button><button class="filter-chip">Sem custo</button><button class="filter-chip">outdoor</button></div></div><div class="card-grid">{''.join(card(p) for p in places[:6])}</div></div><div class="map-mock" role="img" aria-label="Mapa mock">{''.join(f'<span class="map-pin" style="left:{15+(i*20)%70}%;top:{18+(i*27)%65}%">●</span>' for i in range(7))}</div></div></div>'''
(OUT/'explorar.html').write_text(shell('Explorar',explore))
p=places[0]; lugar=f'''<div class="container"><section class="section-sm detail-hero"><div class="detail-media media ratio-hero"><img src="assets/hero-16x9.svg"></div><div class="detail-summary"><span class="eyebrow">Ponto turístico fictício</span><h1>{p['name']}</h1><p class="muted">{p['shortDescription']}</p><div class="cluster"><span class="badge">{p['environment']}</span><a class="button" href="roteiro.html">Adicionar ao roteiro</a></div></div></section><section class="section two-col"><div><h2>Contexto editorial</h2><p>{p.get('longDescription',p['shortDescription'])}</p></div><aside class="aside-card"><span class="eyebrow">Planeje</span><p>{p['openingHours']['text']}</p><p>{p['durationMinutes']} min</p></aside></section></div>'''; (OUT/'lugar.html').write_text(shell('Lugar',lugar))
p=next(x for x in places if x['commercialRelation']=='partner'); parceiro=f'''<div class="container"><section class="section-sm detail-hero"><div class="detail-media media ratio-hero"><img src="assets/hero-16x9.svg"></div><div class="detail-summary"><span class="eyebrow">Parceiro fictício</span><h1>{p['name']}</h1><p class="muted">{p['shortDescription']}</p><span class="badge success">Visita registrada</span></div></section><section class="section two-col"><div><h2>Experiências</h2><div class="aside-card">Conteúdo comercial separado do template turístico.</div></div><aside class="aside-card"><h3>Contatos DEMO</h3><p>example.invalid</p></aside></section></div>'''; (OUT/'parceiro.html').write_text(shell('Parceiro',parceiro))
place_by={p['id']:p for p in places}; day=t['days'][0]; roteiro=f'''<div class="container section"><div class="section-head"><span class="eyebrow">Roteiro demo</span><h1>Sua viagem em blocos editáveis</h1></div><div class="route-layout"><div class="timeline">{''.join(f'<article class="trip-stop"><span class="eyebrow">{i["startsAt"]} · {i["durationMinutes"]} min</span><h3>{place_by[i["placeId"]]["name"]}</h3><div class="trip-actions"><button class="button secondary">Mover +30 min</button><button class="button secondary">Trocar</button></div></article>' for i in day['items'])}</div><aside class="context-panel aside-card"><h3>Clima DEMO</h3><p>21°C · parcialmente nublado</p></aside></div></div>'''; (OUT/'roteiro.html').write_text(shell('Roteiro',roteiro))
calendar=f'''<div class="container section"><div class="section-head"><span class="eyebrow">Calendário</span><h1>O mesmo roteiro em outra leitura</h1></div><div class="calendar-toolbar"><button class="button secondary">Dia</button><button class="button">Semana</button><button class="button secondary">Mês</button></div><section class="calendar-week-grid">{''.join(f'<article class="calendar-column"><strong>Dia {di+1}</strong>'+''.join(f'<div class="calendar-item"><strong>{i["startsAt"]}</strong><div>{place_by[i["placeId"]]["name"]}<div class="state-label">planejado</div></div></div>' for i in d['items'])+'</article>' for di,d in enumerate(t['days']))}</section></div>'''; (OUT/'calendario.html').write_text(shell('Calendário',calendar))
passport=f'''<div class="container section"><div class="section-head"><span class="eyebrow">Meu Passaporte</span><h1>Memória da viagem</h1></div><div class="passport-stage"><div class="passport-book"><section class="passport-page active" data-page="01"><span class="eyebrow">PASSAPORTE DE VALIDAÇÃO</span><h2>Identificação</h2><p><strong>Viajante Demo</strong></p><div class="route-map-placeholder">Elemento territorial fictício</div></section><section class="passport-page active" data-page="02"><span class="eyebrow">VIAGEM ATUAL</span><h2>Bilhete da viagem</h2><div class="passport-ticket"><strong>Serra Negra · SET 2026</strong><p>3 dias · conteúdo sintético</p></div></section></div><div class="passport-nav"><button class="button secondary">←</button><span class="badge">Páginas 1–2</span><button class="button secondary">→</button></div></div></div>'''; (OUT/'passaporte.html').write_text(shell('Passaporte',passport))
admin=f'''<div class="admin-shell"><aside class="admin-nav"><strong>Admin</strong><a>Visão geral</a><a>Lugares</a><a>Experiências</a><a>Parceiros</a><a>Eventos</a></aside><div class="admin-main"><span class="eyebrow">Control plane</span><h1>Admin operacional</h1><div class="status-grid"><div class="status-card"><strong>{len(places)}</strong><div>Lugares</div></div><div class="status-card"><strong>{len(c['partners'])}</strong><div>Parceiros</div></div><div class="status-card"><strong>{len(c['events'])}</strong><div>Eventos</div></div><div class="status-card"><strong>{len(c['categories'])}</strong><div>Categorias</div></div></div><section class="section-sm"><h2>Editor reutilizável</h2><div class="card card-body form-grid"><div class="field"><label>Nome</label><input class="input" value="Café Neblina Alta"></div><div class="field full"><label>Descrição curta</label><textarea class="textarea">Conteúdo demo editável</textarea></div></div><div class="admin-actions"><button class="button">Salvar rascunho</button><button class="button secondary">Preview</button><button class="button">Publicar</button></div></section></div></div>'''; (OUT/'admin.html').write_text(shell('Admin',admin))
print('Static preview generated:', OUT)
