import {spawn} from 'node:child_process';import {existsSync,mkdirSync,writeFileSync} from 'node:fs';import {join} from 'node:path';
const out='artifacts/validation';mkdirSync(out,{recursive:true});const npm=process.platform==='win32'?'npm.cmd':'npm';const results=[];
const knownSecrets=['SESSION_SECRET','IDENTITY_PEPPER','TOURIST_PASSWORD','PARTNER_PASSWORD','ADMIN_PASSWORD','DATABASE_URL'].map(k=>process.env[k]).filter(Boolean);
function redactLog(input){let text=String(input);for(const secret of knownSecrets)text=text.split(secret).join('[redacted]');return text.replace(/(postgres(?:ql)?:\/\/[^:\s/]+:)[^@\s/]+@/gi,'$1[redacted]@').replace(/((?:authorization|cookie|token|secret|password)\s*[:=]\s*)[^\s,;]+/gi,'$1[redacted]').replace(/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g,'[redacted-email]').replace(/(?:^|\s)\+?\d[\d\s().-]{7,}\d(?=\s|$)/g,' [redacted-phone]').replace(/\/mnt\/data\/[^\s'\"]+/g,'[redacted-path]');}
async function run(name,cmd,args){const chunks=[];const code=await new Promise(resolve=>{const p=spawn(cmd,args,{stdio:['ignore','pipe','pipe'],env:{...process.env,DB_MODE:process.env.DB_MODE||'pglite',PGLITE_PATH:process.env.PGLITE_PATH||'.data/validation',SESSION_SECRET:process.env.SESSION_SECRET||'validation-session-secret-with-at-least-32-characters',IDENTITY_PEPPER:process.env.IDENTITY_PEPPER||'validation-identity-pepper-with-at-least-32-characters',TOURIST_EMAIL:process.env.TOURIST_EMAIL||'turista@passaporte.local',TOURIST_PASSWORD:process.env.TOURIST_PASSWORD||'validation-tourist-password',PARTNER_EMAIL:process.env.PARTNER_EMAIL||'parceiro@passaporte.local',PARTNER_PASSWORD:process.env.PARTNER_PASSWORD||'validation-partner-password',PARTNER_ID:process.env.PARTNER_ID||'partner-cafe-neblina',ADMIN_EMAIL:process.env.ADMIN_EMAIL||'admin@passaporte.local',ADMIN_PASSWORD:process.env.ADMIN_PASSWORD||'validation-admin-password'}});p.stdout.on('data',d=>{chunks.push(d);process.stdout.write(d)});p.stderr.on('data',d=>{chunks.push(d);process.stderr.write(d)});p.on('error',()=>resolve(127));p.on('close',c=>resolve(c??1));});writeFileSync(join(out,`${name}.log`),redactLog(Buffer.concat(chunks).toString('utf8')));results.push({name,status:code===0?'PASS':'FAIL',exitCode:code});return code===0;}
let ok=await run('static',process.execPath,['scripts/validate-static.mjs']);
if(ok)ok=await run('sensitive-scan',process.execPath,['scripts/scan-sensitive.mjs']);
if(ok)ok=await run('sanitization-audit',process.execPath,['scripts/audit-sanitization.mjs']);
if(ok)ok=await run('responsive-audit',process.execPath,['scripts/audit-responsive.mjs']);
if(ok)ok=await run('uxui-audit',process.execPath,['scripts/audit-uxui.mjs']);
if(ok)ok=await run('vercel-audit',process.execPath,['scripts/audit-vercel-build.mjs']);
if(ok)ok=await run('interactions-audit',process.execPath,['scripts/audit-interactions.mjs']);
if(ok)ok=await run('playwright-audit',process.execPath,['scripts/audit-playwright.mjs']);
if(ok&&existsSync('node_modules/typescript/package.json')){for(const [name,args] of [['typecheck',['run','typecheck']],['lint',['run','lint']],['unit',['test']],['prepare',['run','local:prepare']],['build',['run','build']]]){if(!await run(name,npm,args)){ok=false;break;}}if(ok&&existsSync('node_modules/@playwright/test/package.json'))ok=await run('e2e',npm,['run','test:e2e']);}
else results.push({name:'dependency-suite',status:'BLOCKED',detail:'Execute npm ci before the dependency-based suite.'});
writeFileSync(join(out,'SUMMARY.json'),JSON.stringify({at:new Date().toISOString(),status:ok?'PASS':results.some(r=>r.status==='BLOCKED')?'BLOCKED':'FAIL',results},null,2));process.exitCode=ok?0:1;
