import crypto from "node:crypto";
import postgres from "postgres";
import type {AuditEntry, ContentEntity, EntityKind, TrackingEvent, TrackingEventName, TripBundle} from "@/core/domain/types";
import type {EntityRecord,Repository} from "./repository";

function db(){const url=process.env.DATABASE_URL;if(!url)throw new Error("DATABASE_URL ausente");return postgres(url,{max:5});}
const mapRow=(r:any):EntityRecord=>({id:r.id,kind:r.kind,slug:r.slug??undefined,status:r.status,synthetic:r.synthetic,data:r.data,updatedAt:new Date(r.updated_at).toISOString()});
export class PostgresRepository implements Repository{
 mode="postgres" as const;
 async list<T=ContentEntity>(kind:EntityKind,o:{publishedOnly?:boolean}={}){const sql=db();try{const rows=o.publishedOnly?await sql`select * from content_entities where kind=${kind} and status='published' order by id`:await sql`select * from content_entities where kind=${kind} order by id`;return rows.map(mapRow) as EntityRecord<T>[];}finally{await sql.end();}}
 async get<T=ContentEntity>(kind:EntityKind,id:string,o:{draft?:boolean}={}){const sql=db();try{if(o.draft){const d=await sql`select d.entity_id as id,d.kind,e.slug,'draft' as status,e.synthetic,d.data,d.updated_at from content_drafts d join content_entities e on e.id=d.entity_id where d.kind=${kind} and d.entity_id=${id} limit 1`;if(d[0])return mapRow(d[0]) as EntityRecord<T>;}const rows=await sql`select * from content_entities where kind=${kind} and id=${id} limit 1`;return rows[0]?mapRow(rows[0]) as EntityRecord<T>:null;}finally{await sql.end();}}
 async findBySlug<T=ContentEntity>(kind:EntityKind,slug:string,o:{draft?:boolean}={}){const sql=db();try{const rows=await sql`select * from content_entities where kind=${kind} and slug=${slug} limit 1`;if(!rows[0])return null;const base=mapRow(rows[0]);if(o.draft){const d=await sql`select data,updated_at from content_drafts where entity_id=${base.id} limit 1`;if(d[0])return {...base,status:"draft",data:d[0].data,updatedAt:new Date(d[0].updated_at).toISOString()} as EntityRecord<T>;}return base as EntityRecord<T>;}finally{await sql.end();}}
 async createDraft(kind:EntityKind,data:Record<string,unknown>,actor="mock-admin"){const sql=db();try{const id=String(data.id||`${kind}-${crypto.randomUUID().slice(0,8)}`),slug=String(data.slug||id),body={...data,id,synthetic:true};await sql.begin(async tx=>{await tx`insert into content_entities(id,kind,slug,status,synthetic,data) values(${id},${kind},${slug},'draft',true,${tx.json(body)}) on conflict(id) do nothing`;await tx`insert into content_drafts(entity_id,kind,data) values(${id},${kind},${tx.json(body)}) on conflict(entity_id) do update set data=excluded.data,updated_at=now()`;await tx`insert into audit_logs(id,actor,action,entity_kind,entity_id,before_json,after_json) values(${crypto.randomUUID()},${actor},'create_draft',${kind},${id},null,${tx.json(body)})`;});return (await this.get(kind,id,{draft:true}))!;}finally{await sql.end();}}
 async saveDraft(kind:EntityKind,id:string,patch:Record<string,unknown>,actor="mock-admin"){const sql=db();try{const base=await this.get(kind,id,{draft:true});if(!base)throw new Error("Entidade não encontrada");const body={...(base.data as any),...patch,id};await sql.begin(async tx=>{await tx`insert into content_drafts(entity_id,kind,data) values(${id},${kind},${tx.json(body)}) on conflict(entity_id) do update set data=excluded.data,updated_at=now()`;await tx`insert into audit_logs(id,actor,action,entity_kind,entity_id,before_json,after_json) values(${crypto.randomUUID()},${actor},'save_draft',${kind},${id},${tx.json(base.data)},${tx.json(body)})`;});return (await this.get(kind,id,{draft:true}))!;}finally{await sql.end();}}
 async publish(kind:EntityKind,id:string,actor="mock-admin"){const sql=db();try{const draft=await this.get(kind,id,{draft:true});if(!draft||draft.status!=="draft")throw new Error("Nenhum rascunho para publicar");const current=await this.get(kind,id);const body={...(draft.data as any)};await sql.begin(async tx=>{await tx`update content_entities set data=${tx.json(body)},status='published',slug=${String((body as any).slug||draft.slug||id)},updated_at=now() where id=${id} and kind=${kind}`;await tx`delete from content_drafts where entity_id=${id}`;await tx`insert into audit_logs(id,actor,action,entity_kind,entity_id,before_json,after_json) values(${crypto.randomUUID()},${actor},'publish',${kind},${id},${tx.json(current?.data??null)},${tx.json(body)})`;});return (await this.get(kind,id))!;}finally{await sql.end();}}
 async archive(kind:EntityKind,id:string,actor="mock-admin"){const sql=db();try{const cur=await this.get(kind,id);if(!cur)throw new Error("Entidade não encontrada");const body={...(cur.data as any)};await sql.begin(async tx=>{await tx`update content_entities set data=${tx.json(body)},status='archived',updated_at=now() where id=${id} and kind=${kind}`;await tx`delete from content_drafts where entity_id=${id}`;await tx`insert into audit_logs(id,actor,action,entity_kind,entity_id,before_json,after_json) values(${crypto.randomUUID()},${actor},'archive',${kind},${id},${tx.json(cur.data)},${tx.json(body)})`;});return (await this.get(kind,id))!;}finally{await sql.end();}}
 async history(kind:EntityKind,id:string){const sql=db();try{const rows=await sql`select * from audit_logs where entity_kind=${kind} and entity_id=${id} order by timestamp desc`;return rows.map((r:any)=>({id:r.id,actor:r.actor,action:r.action,entityKind:r.entity_kind,entityId:r.entity_id,timestamp:new Date(r.timestamp).toISOString(),before:r.before_json,after:r.after_json})) as AuditEntry[];}finally{await sql.end();}}
 async getTripBundle(id:string){const sql=db();try{const rows=await sql`select data from trip_bundles where id=${id} limit 1`;return rows[0]?.data as TripBundle??null;}finally{await sql.end();}}
 async saveTripBundle(bundle:TripBundle){const sql=db();try{await sql`insert into trip_bundles(id,synthetic,data,updated_at) values(${bundle.trip.id},true,${sql.json(bundle)},now()) on conflict(id) do update set data=excluded.data,updated_at=now()`;}finally{await sql.end();}}
 async track(name:TrackingEventName,payload:Record<string,unknown>){const sql=db();try{const ev={id:crypto.randomUUID(),name,payload,createdAt:new Date().toISOString()};await sql`insert into tracking_events(id,event_name,payload,created_at) values(${ev.id},${name},${sql.json(payload)},${ev.createdAt})`;return ev;}finally{await sql.end();}}
 async recentTracking(limit=100){const sql=db();try{const rows=await sql`select * from tracking_events order by created_at desc limit ${limit}`;return rows.map((r:any)=>({id:r.id,name:r.event_name,payload:r.payload,createdAt:new Date(r.created_at).toISOString()})) as TrackingEvent[];}finally{await sql.end();}}
}
